### ISSUE TITLE
feat(developer): escaping should be \u{…} not \uXXXX 🙀

### ISSUE THREAD

**Issue by srl295** [keymanapp/keyman#10319]
- [X] use proper escaping, not `\uXXXX`
- [x] reject `\uXXXX`
- [X] convert `\u{X}` to `\uXXXX` - even for supplemental
- [X] escape marker matches
- [x] It turns out that we need to use char literals instead of escapes so that normalization works properly.  `e<marker>\\u0300\\u0320` needs to actually be `e<marker>U+0300U+0320` so that the normalization can apply - it won't apply to the escaped chars! So probably make a list of which chars are safe to unescape (skipping parens, brackets etc).
- [x] handle \u{...} in reorders

- split from [#9121](https://github.com/keymanapp/keyman/issues/9121)

**Comment by srl295** [comment]
the "forbid \u...." moved to #10389
