### ISSUE TITLE
meta(android): MS review of Android UX issues

### ISSUE THREAD

**Issue by darcywong00** [keymanapp/keyman#11007]
Follows #7161 
@MakaraSok compiled a list of UX issues on Keyman for Android

https://docs.google.com/document/d/1R2wloTnm7Yjh53v58vMCEfvHS679snKYsY5nGWu5KcQ/edit#heading=h.kjwind3vnqhn

I'll gradually convert these into linked issues

- [ ] Key size is smaller than Gboard/Samsung keys
- [ ] next word prediction for Khmer
- [ ] next word prediction for Khmer
- [ ] settings right above the OSK
- [ ] hint for longpress and release to type
- [ ] function keys should be in a set location on the keyboard, so that it’s easier for users to switch from one keyboard to another, right now the keyboard designer took the liberty of placing them wherever they want.
pick a set location of each of them and make it immoveable just like those in the desktop OSK version.
keyboard help should easily be accessible from where they use the keyboard, i.e. keyboard switcher when the globe key is triggered. 
- [ ] switching between keyboards is not seamless comparing with the default keyboard the device comes with, i.e. Samsung’s.
the keyboard should be just switched, no flickering. try and switch between keyboards using Keyman and then Samsung’s or Gboard’s
- [ ] Emoji, is a major turn off when it cannot be seamlessly accessed without switching to other keyboards. Users have been asking for it for a while, but the voice hasn’t been “heard”.
- [ ] theme personalization, keyboard background image/color
- [ ] dark mode and light mode for the OSK
- [ ] floating OSK, why it’s always waaay down at the bottom and not where I want. Phone form factors are getting bigger and longer/taller, please.
- [ ] delete a word with a trailing ZWSP, it’s annoying to delete a word by pressing the back space two times to get to the character to delete. pick a word from the suggestion banner and then try to delete the last character, only get to the ZWSP instead of the last character/word.

-----

More from testers....
