### ISSUE TITLE
refactor (Windows,Linux,mac): request for code changes in several files used throughout mcompile for Windows,Linux and mac

### ISSUE THREAD

**Issue by SabineSIL** [keymanapp/keyman#11802]
### Describe the solution you'd like

While reviewing mnemonic keyboard layout-linux PR[#9384](https://github.com/keymanapp/keyman/pull/9384) some ideas came up about how to improve already existing code. The code is running fine so there is no immediate urgency to address this issue right away.

The code mentioned is used in mcompile-Windows, mcompile-Linux and mcompile-Mac (and possibly in other places as well).
In order to keep this specific code the same across all platforms, no changes have been made in _any_ of the mcompile versions for now.
Once this issue is addressed, improvements should be made in mcompile-Windows, mcompile-Linux [PR #9384](https://github.com/keymanapp/keyman/pull/9384)  and mcompile-Mac [PR #11334](https://github.com/keymanapp/keyman/pull/11334) 

Changes should be made in:

**util_filesystem.cpp**
-  [ use __FUNCTION__ macro instead of hard coding the method name](https://github.com/keymanapp/keyman/pull/9384#discussion_r1613254679)
- [unneccessary code ](https://github.com/keymanapp/keyman/pull/9384/files#r1613263494)
- [mount in the else branch ](https://github.com/keymanapp/keyman/pull/9384#discussion_r1613267705)
- [unreachable code](https://github.com/keymanapp/keyman/pull/9384/files#r1613283398)

**mc_import_rules.cpp**

- [rename SGCAPS](https://github.com/keymanapp/keyman/pull/9384#discussion_r1625790119)
- [possibility of buffer overflow](https://github.com/keymanapp/keyman/pull/9384#discussion_r1627797712)
- [initialize *key->dpContext with NULL ](https://github.com/keymanapp/keyman/pull/9384#discussion_r1627807274)
- [another initialize *key->dpContext with NULL ](https://github.com/keymanapp/keyman/pull/9384#discussion_r1627804048)
- [use copy()-method ](https://github.com/keymanapp/keyman/pull/9384#discussion_r1627814029)
- [use std::u16string instead of PKMX_WCHAR](https://github.com/keymanapp/keyman/pull/9384#discussion_r1627823950)

**mcompile.cpp**
- [move forward declaration](https://github.com/keymanapp/keyman/pull/9384#discussion_r1627854203)

**mc-kmxfile.cpp**

- [compare dwFileVersion with VERSION_MIN /VERSION_MAX always returns FALSE](https://github.com/keymanapp/keyman/pull/9384#discussion_r1631040600)

### Keyman apps

- [ ] Keyman for Android
- [ ] Keyman for iPhone and iPad
- [X] Keyman for Linux
- [X] Keyman for macOS
- [X] Keyman for Windows
- [ ] Keyman Developer
- [ ] KeymanWeb
- [ ] Other - give details at bottom of form
