### ISSUE TITLE
chore(core): replace std::codecvt in module u16 

### ISSUE THREAD

**Issue by SabineSIL** [keymanapp/keyman#11922]
### Describe the solution you'd like

  std::codecvt will be deprecated by C++17. We still use std::codecvt in the module u16 at 3 locations:

- /developer/src/kmcmplib/src/
-  mcompile-linux
-  mcompile-mac

std::codecvt needs to be replaced there. Tests would also be good

### Keyman apps

- [ ] Keyman for Android
- [ ] Keyman for iPhone and iPad
- [X] Keyman for Linux
- [X] Keyman for macOS
- [X] Keyman for Windows
- [X] Keyman Developer
- [ ] KeymanWeb
- [ ] Other - give details at bottom of form

**Comment by SabineSIL** [comment]
PR #12171 / PR #12107 addressed this issue
