### ISSUE TITLE
feat(developer): kmc-generate and kmc-copy consolidation

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyman#12641]
Consolidating TODO lists from #11014, #12555

## TODO from #11014 
- [ ] keymanapp/help.keyman.com#1335 -- update kmconvert ref 
- [ ] validate targets (basic-generator.ts TODO-GENERATE)
- [ ] additional validation of ids for keyboard and model filenames (e.g. casing)
- [ ] documentation
- [ ] generate icons (keyman-keyboard-generator.ts TODO-GENERATE, also tests)
- [ ] additional test for transform (test-basic-generator.ts TODO-GENERATE)

## TODO from #12555

**Comment by mcdurdin** [comment]
Moving remaining TODO items here to January

**Comment by mcdurdin** [comment]
> * generate icons (keyman-keyboard-generator.ts TODO-GENERATE, also tests)

This unfortunately is problematic:
1. Keyman for Windows does not support png-format icons (because Delphi version we are stuck on doesn't support them)
2. node.js ico generation (e.g. using Jimp) does not support bmp-format icons properly.

We could fix either of these but it's a bit of effort, and probably not worth it for an icon that will probably be thrown away anyway. So for now, we will not support automatic generation of icons.

**Comment by mcdurdin** [comment]
I think the remaining unfinished tasks can wait until 19.0.
