### ISSUE TITLE
[Android] 12.0 Pre-beta checklist

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyman#1904]
# Keyman for Android Acceptance Test Procedures #

These test procedures are to be run before any beta or stable build is published. Copy these checklists of tests before PRs are merged into the beta and stable branches.

## Visual Inspection of master branch
- [x] ![Build Status](https://build.palaso.org/app/rest/builds/buildType:(id:KeymanAndroid_Build)/statusIcon) Verify latest CI build of [master](https://build.palaso.org/viewType.html?buildTypeId=KeymanAndroid_Build) is successful 
- [x] Verify `android/history.md` contains all the current changes

## Gather Assets for Testing ##
- [x] Physical Android phone (record device's Android -- version 4.4 KitKat or later)
- [x] External bluetooth keyboard that's paired with the Android device

## Setup Steps ##
- [x] Uninstall previous version of Keyman on the device (don't forget to reset user settings for the app; in Android Pie: Settings>Storage>Other apps>Keyman>Clear Storage)
- [x] Install test build APK
- [x] On device, disable internet connectivity
- [x] Start Keyman and select **Add a keyboard for your language**
- [x] Verify error message "Cannot connect to Keyman server!" is displayed
- [x] Click OK to dismiss.  Close Keyman app
- [x] On device, enable internet connectivity
- [x] Start Keyman
- [x] On initial **Get Started** menu, select "Enable Keyman as system-wide keyboard" and do any necessary system steps to enable Keyman

----

### Get Started ###
- [x] Verify touching **Add a keyboard for your language** pulls up the **Add New Keyboard** menu
- [x] Verify touching **Enable Keyman as system-wide keyboard** pulls up system dialog for keyboards
- [x] Verify **Set Keyman as default keyboard** can be toggled on/off
- [x] Verify touching **More info** brings up the version page and Keyman Help page
- [x] Clear **Show 'Get Started' on startup** checkbox, close and re-open Keyman, and verify **Get Started** menu does not appear

### Add New Keyboard ###
This menu is accessed via **Get Started** menu or the Settings button on the OSK
- [x] On the device, enable internet connectivity
- [x] Verify a new keyboard can be downloaded and selected
- [x] On the device, disable internet connectivity
- [x] Attempt to download another keyboard and verify device immediately displays a msg "No internet connection"
- [x] On the device, re-enable internet connectivity

### Settings ###
- [x] Installed Languages ... Add Language
- [x] Select an installed language ... Add (another) Keyboard
- [x] Select an installed language ... Dictionary
- [ ] Turn on/off 'Enable Predictions' and validate each
- [x] Turn on/off 'Enable Corrections' and validate each
- [x] Validate that when both predictions and corrections are off, banner is not visible
- [x] Add/Remove dictionaries - validate
- [x] If multiple dictionaries are available, test swapping between them

### Share ###
- [x] Type and verify text can be shared to external app

### Keyman Browser ###
- [x] On default page, click on text field and set system keyboard to Keyman
- [ ] Verify can type with Keyman as system keyboard
- [x] Close and reopen Keyman app

### Text Size ###
- [x] Verify text can be rescaled from Text Size 16 to 72

### Clear Text ###
- [x] Verify text can be cleared

### Info ###
- [x] Verify Keyman Android version briefly appears and record the version
- [x] Verify Help documentation appears with base URL https://help.keyman.com/

----

### In-app Keyboards
These tests are run in the context of typing in the Keyman app

#### English(EuroLatin SIL)
- [x] In portrait orientation, verify OSK is visible and fills the width the bottom of the screen
- [x] Verify long-press `q` key works
- [x] Verify long-press `p` key works
- [x] Verify uppercase layer can be selected via `SHIFT`
- [x] Verify number layer can be selected via `123`
- [x] Verify long-press `1` key works
- [x] Verify long-press `0` key works
- [x] Verify backspace, space, and enter keys work
- [x] Verify *Khmer* -> *Khmer Angkor* keyboard can be added via Settings menu
- [x] Repeat in landscape orientation

#### Non-Latin script Keyboard
- [x] In the app, add/select a random non-Latin script keyboard
- [x] Verify OSK is visible
- [x] Test several keys and modifiers and verify Latin characters are not appearing.

### System Keyboards
These tests are run with Keyman selected as a system keyboard, and in the context of typing in an external app (like Google Keep)

#### English(EuroLatin SIL)
- [x] In portrait orientation, verify OSK is visible and fills the width the bottom of the screen
- [x] Verify long-press `q` key works
- [x] Verify long-press `p` key works
- [x] Verify uppercase layer can be selected via `SHIFT`
- [x] Verify number layer can be selected via `123`
- [x] Verify long-press `1` key works
- [x] Verify long-press `0` key works
- [x] Verify backspace, space, and enter keys work
- [x] Verify a random non-Latin script keyboard can be added via globe button
- [x] Repeat in landscape orientation

#### "Close Keyman" and Switch to next system keyboard
This tests the "CLOSE KEYMAN" button that's only available when Keyman is a system keyboard.
- [x] Click the globe button
- [x] Verify the bottom left of the Keyboards picker has a button "CLOSE KEYMAN"
- [x] Click the "CLOSE KEYMAN" button
- [x] Verify the Keyman system keyboard is closed
- [x] Display the OSK and verify the next system keyboard is enabled (e.g Google Gboard)

#### External (Bluetooth) keyboard
This test is run with an external bluetooth keyboard paired to the device
- [x] Start with English(EuroLatin SIL) as the selected keyboard
- [x] Verify OSK is not visible
- [x] Verify can type with numbers, letters, and punctuation
- [x] Verify `caps lock` has no effect when typing
- [x] Verify long-press on a character repeats that character
- [x] Verify `tab` toggles to next field
- [x] Verify `enter` adds a newline
- [x] Verify `backspace` removes a character
- [x] Verify `ctrl` + `tab` brings up the menu to add new keyboard
- [x] Select a non-Latin keyboard
- [x] Resume typing and verify new script appears

----

### KMP distribution
- [x] Reset app settings (in Android Pie: Settings>Storage>Other apps>Keyman>Clear Storage)
- [ ] Verify kmp [distribution](https://help.keyman.com/developer/10.0/guides/distribute/) successfully installs<br/>
 Example: [Khmer Angkor](https://downloads.keyman.com/keyboards/khmer_angkor/1.0.2/khmer_angkor.kmp)

----

## What's New Tests
- [x] Refer to the new changes in `android/history.md` and verify functionality

**Comment by mcdurdin** [comment]
1. [Settings] Back from Settings/Installed Languages/Installed Language takes you to Settings instead of Settings/Installed Languages
2. [Info] Info page opens an unversioned link to the app help. Should be versioned.
3. [Get Started] The "Show Get Started" checkbox is only touchable on the checkbox, not the label, unlike the items above it
4. [Menu] The popup menu labels are not aligned horizontally. Looks ugly.
5. Turning off 'Enable Predictions' doesn't stop predictions from being displayed. It's also a bit weird conceptually :)
6. Default keyboard and Enable System Keyboard should really be available from Settings
7. !! Switching system keyboards gave me the following JS errors:
```
      Uncaught ReferenceError: resetContext is not defined
          at <anonymous>:1:1
      2 x VM27:1 Uncaught ReferenceError: updateKMText is not defined
          at <anonymous>:1:1
      VM28:1 Uncaught ReferenceError: updateKMSelectionRange is not defined
          at <anonymous>:1:1
      9 x keyboard.html:1 Uncaught ReferenceError: setKeymanLanguage is not defined
          at <anonymous>:1:1
```
8. In Keyman Browser, typing is horribly slow, seconds per keystroke
9. Starting Keyman, the version info scrolls into view for a moment then disappears again. Should be visible on splash always.
    See [Starting Keyman - version text shows and disappears.mp4](https://drive.google.com/a/sil.org/file/d/1k6sMQ23Pa9sogmZVS-6Hs6YJf_UmWq9x/view?usp=sharing)


10. Typing <ser> or <yet> or many other <xex> on Khmer Angkor keyboard triggers a vibrate? Note: text appears correct. why vibrate?
11. Unable to install KMP file using Chrome or File Browser (Nokia 3)

**Comment by jahorton** [comment]
>     7. !! Switching system keyboards gave me the following JS errors:
> 
> 
> ```
>       Uncaught ReferenceError: resetContext is not defined
>           at <anonymous>:1:1
>       2 x VM27:1 Uncaught ReferenceError: updateKMText is not defined
>           at <anonymous>:1:1
>       VM28:1 Uncaught ReferenceError: updateKMSelectionRange is not defined
>           at <anonymous>:1:1
>       9 x keyboard.html:1 Uncaught ReferenceError: setKeymanLanguage is not defined
>           at <anonymous>:1:1
> ```

More fodder for #1884, it seems.

**Comment by jahorton** [comment]
Toward that end, any chance you can give me the exact specs you ran that test under?  This has been incredibly difficult for me to reproduce on demand, so anything that could help me do so would be quite appreciated.

**Comment by mcdurdin** [comment]
> Toward that end, any chance you can give me the exact specs you ran that test under? This has been incredibly difficult for me to reproduce on demand, so anything that could help me do so would be quite appreciated.

1. Testing on Android 9 (Pie) on Nokia 3 TA-1032
1. Clean install of app (including resetting settings via Settings>Storage>Other apps>Keyman>Clear Storage)
2. Install Khmer Angkor keyboard and Dvorak
3. Swap between system keyboards.

The error can be viewed in Chrome Web Inspector.

It seems there is an error loop in some circumstances; e.g. writing up these steps now led to Keyman freezing, apparently because it is continually reloading the keyboard page and crashing on load.

**Comment by mcdurdin** [comment]
All dot points broken out into separate issues now.
