### ISSUE TITLE
[iOS] 12.0 Pre-beta checklist 

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyman#1906]
# Keyman for iPhone and iPad Acceptance Test Procedures #

These test procedures are to be run before any beta or stable build is published. Copy these checklists of tests before PRs are merged into the beta and stable branches.

## Visual Inspection of master branch
- [x] ![Build Status](https://build.palaso.org/app/rest/builds/buildType:(id:Keyman_iOS_Master)/statusIcon) Verify latest CI build of [master](https://build.palaso.org/viewType.html?buildTypeId=Keyman_iOS_Master) is successful
- [x] Verify `ios/history.md` contains all the current changes

## Gather Assets for Testing ##
- [x] Record device's iOS version 
- [x] Ensure the device is properly configured for testing and is registered with TestFlight.

At this time, Keyman for iOS does not support external keyboard input.

## Setup Steps ##
- [x] Uninstall previous version of Keyman on the device
- [x] Install test build IPA
- [x] On device, disable internet connectivity
- [x] Start Keyman and select **Add a keyboard for your language**
- [x] Verify error message "Could not reach Keyman server!" is displayed
- [x] Click OK to dismiss.  Close Keyman app
- [x] On device, enable internet connectivity
- [x] Start Keyman
- [x] On initial **Get Started** menu, select "Enable Keyman as system-wide keyboard" and do any necessary system steps to enable Keyman

### Get Started ###
- [x] Verify touching **Add a keyboard for your language** pulls up the **Add New Keyboard** menu
- [x] Verify touching **Enable Keyman as system-wide keyboard** pulls up accurate instructions.
- [x] Verify touching **More info** brings up an accurate version and "Getting Started" page.
- [x] Set **Don't show again** to checked, close and re-open Keyman, and verify **Get Started** menu does not appear

### Settings ###
- [x] Installed Languages ... Add Language
- [x] Select an installed language ... Add (another) Keyboard
- [x] Select an installed language ... Dictionary
- [x] Turn on/off 'Enable Predictions' and validate each
- [x] Turn on/off 'Enable Corrections' and validate each
- [ ] Validate that when both predictions and corrections are off, banner is not visible
- [x] Add/Remove dictionaries - validate
- [x] If multiple dictionaries are available, test swapping between them

Note that the stated version will be inaccurate if run within the Simulator instead of on a physical device.

### Add New Keyboard ###
This menu is accessed via **Get Started** menu or **Settings** menu
- [x] On the device, enable internet connectivity
- [x] Verify a new keyboard can be downloaded and selected
- [x] Return to the text input screen and confirm that it operates correctly.
- [x] Without changing selected language, confirm that it can be cleanly deleted via the Settings menu.
- [x] Confirm that another keyboard is correctly selected afterward.

### Share ###
- [x] Type and verify text can be copied and shared to external app

### Keyman Browser ###
- [x] On default page, click on text field and set system keyboard to Keyman
- [x] Verify can type with Keyman as system keyboard
- [x] Close and reopen Keyman app

### Text Size ###
- [x] Verify text can be rescaled from Text Size 16 to 72

### Clear Text ###
- [x] Verify text can be cleared

### Info ###
- [x] Verify that the Keyman IOS version briefly appears and record the version
- [x] Verify that the Info menu options matches that of the **More Info...** option from the **Get Started** menu option.

## Keyboard Tests

- [x] Confirm all keyboard tests below have been performed in both portrait and landscape modes.

### **English (Eurolatin2)** in-app
- [x] In portrait orientation, verify that the OSK appears and fills the width the bottom of the screen
- [x] Verify long-press `q` key works
- [x] Verify long-press `p` key works
- [x] Verify uppercase layer can be selected via `SHIFT`
- [x] Verify number layer can be selected via `123`
- [x] Verify long-press `1` key works
- [x] Verify long-press `0` key works
- [x] Verify backspace, space, and enter keys work
- [x] Verify **French: French** keyboard can be added via Settings

Note that the shown EuroLatin2 is a highly customized keyboard explicitly designed for mobile.

### **French: French** in-app
- [x] Verify that long-press `SHIFT` key works and allows selection of layers.
- [x] Ensure key inputs from the right-most selectable long-press layer works.
- [x] Revert to the default layer and ensure basic key inputs work.
- [x] Use the globe key to access the keyboard menu.
- [x] From the `Settings > Languages > French > French >` menu, follow the "Help link" and ensure it connects properly to help.keyman.com.
- [x] Returning to the app, delete the **French: French** keyboard via Settings.

Note that the specified French keyboard lacks a customized keyboard layout for mobile, relying instead upon the default one provided by KeymanWeb.

### Predictive Text
- [ ] **TODO**

## What's New Tests
- [x] Refer to the new changes in `ios/history.md` and verify functionality

**Comment by mcdurdin** [comment]
iOS version = 12.3.1; iPhone 7

1. When starting Keyman for the very first time, the banner is blank (startup - blank banner and Tap Here location.png)
2. When starting Keyman for the very first time, the "Tap here to change keyboard" popup is misaligned (startup - blank banner and Tap Here location.png)
3. "Get Started" is only shown if system keyboard is not already installed.
4. Switching back into Keyman led to a blank OSK (blank keyboard after swapping apps.png)
5. Switching back out and in again led to a wrongly sized OSK (misshapen keyboard after swapping apps.png)
6. Banner is visible even for keyboards that have no dictionaries
7. If an internet connection error is shown, the Install New Keyboard view should be closed after clicking OK.
8. English MTNT model is not installed by default (should it be??)
9. Info page is not versioned and points to http, not https
10. "Add Keyboard" from "Installed Language" view leads to showing the whole list initially, then the sublist. Clicking Back then shows the whole list again. The whole list should never be shown.
11. Accepting first suggestion on blank text then the next suggestion replaces the first: Accept "the", then "there". 
12. Disabling predictions, just like on Android (#1904), doesn't disable them (and doesn't actually make much sense!)
13. Can still delete a keyboard from the picker by swiping left.
14. Conversely, cannot delete a keyboard or model or language in Settings by swiping left.
15. Subtext on Settings shows "1 languages installed" instead of "1 language installed"
16. Settings menu briefly shows wrong number of installed languages after uninstalling last keyboard for a language.
17. System keyboard banner position is crammed against top of OSK instead of having small margin (position of banner.png)

**Comment by mcdurdin** [comment]
All dot points broken out into separate issues now.
