### ISSUE TITLE
[Windows][Developer] 13.0 Pre-beta checklist

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyman#2525]
# Keyman Desktop and Keyman Developer Acceptance Test Procedures #

These test procedures are to be run before any beta or stable build is published. Copy these checklists of tests before PRs are merged into the beta and stable branches.

## Visual Inspection of master/beta branch
- [x] ![Build Status](https://build.palaso.org/app/rest/builds/buildType:(id:Keyman_Build)/statusIcon) Verify latest CI build of [master](https://build.palaso.org/viewType.html?buildTypeId=Keyman_Build) is successful 
- [x] Verify `windows/src/desktop/history.md` and `windows/src/developer/history.md` contain all the current changes

## Gather Assets for Testing ##
- [ ] Windows 7 (x86) - VM or physical okay
- [ ] Windows 7 (x64) - VM or physical okay
- [ ] Windows 8.1 (x64) - VM or physical okay
- [x] Windows 10 (x64) - VM or physical okay

## Setup Steps ##
- [x] Uninstall previous versions of Keyman Desktop and Keyman Developer on the system
- [x] Restart system, install updates

# Keyman Desktop #

## Basic installation ##
- [x] Install test build keymandesktop-a.b.c.d.exe
- [x] Make sure Keyman Desktop is started and visible in the Notification area
- [x] Start Keyman Configuration
- [x] Click Download Keyboard, select a keyboard from the download dialog and install it
- [x] If the package includes a readme file, verify that it appears in the install window.
- [x] If the package includes a welcome file, verify that it appears after installation.
- [x] Click OK to close Keyman Configuration
- [x] Start Notepad
- [x] Verify that the newly installed keyboard appears in the Keyman menu and can be selected

## Install a package from disk ##
- [x] Locate a .kmp file on disk and double-click to install it
- [x] If the package includes a readme file, verify that it appears in the install window.
- [x] If the package includes a welcome file, verify that it appears after installation.
- [x] Start Notepad
- [x] Verify that the keyboard appears in the Keyman menu

## Test keyboard output ##
- [x] Start Notepad and select a Keyman keyboard (testing Legacy integration)
- [x] Verify that various test sequences are output correctly
- [x] Start Word and select a Keyman keyboard (testing TSF integration)
- [x] Verify that various test sequences are output correctly

## On Screen Keyboard tests ##
- [x] Click Keyman icon in Notification area, select On Screen Keyboard
- [x] Verify that OSK displays correctly for selected Keyman keyboard
- [x] Verify that typing characters by clicking on OSK produces expected output

## What's New Tests
- [x] Refer to the new changes in `windows/src/desktop/history.md` and verify functionality

# Keyman Developer
- [x] Verify that Keyman Developer starts
- [x] Open a .kpj project, load keyboards and verify that you can compile them

## What's New Tests
- [x] Refer to the new changes in `windows/src/developer/history.md` and verify functionality

**Comment by mcdurdin** [comment]
# Desktop

* No issues found.

# Developer

A number of non-blocking issues with new functionality:

- [ ] Recent projects menu has malformed entries (but they work): 
![image](https://user-images.githubusercontent.com/4498365/73126921-c4936280-400c-11ea-9850-08b00c982841.png)
- [ ] Developer 13.0 help is missing
- [ ] F7 from project window did not compile keyboards (but menu item worked)

## Keyboard editor

- [ ] Using new unquoted format hotkeys results in "too complex to display" visual layout editor
- [ ] F7 did not compile from anywhere in keyboard editor (but using menu item did; F5 also worked)
- [ ] Dropping characters from charmap onto OSK drops codes by default (chars dropped into touch editor, layout editor)

## Lexical model editor

- [ ] Project template still includes wordlist.tsv in kpj
- [ ] Creating a new file resulted in the wordlist editor being unable to edit the file:
![image](https://user-images.githubusercontent.com/4498365/73126877-551d7300-400c-11ea-886c-8e603bc84e22.png)
