### ISSUE TITLE
[mac] 13.0 Pre-beta checklist

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyman#2526]
# Keyman for macOS Acceptance Test Procedures #

These test procedures are to be run before any beta or stable build is published. Copy these checklists of tests before PRs are merged into the beta and stable branches.

## Visual Inspection of master branch
- [x] ![Build Status](https://build.palaso.org/app/rest/builds/buildType:(id:Keyman_iOS_Master)/statusIcon) Verify latest CI build of [master](https://build.palaso.org/viewType.html?buildTypeId=KeymanMac_Master) is successful
- [x] Verify `mac/history.md` contains all the current changes

## Setup Steps ##
- [x] Ensure the device is running the latest version of macOS.
- [x] Uninstall previous version of Keyman on the device
- [x] Install latest master build (or whatever version is to be tested) of Keyman on the device

## Basic smoke test ##
- [x] Verify that the version displayed in the About box is correct.
- [x] On device, turn Wifi off and/or disconnect Ethernet cable
- [x] Activate Keyman and select Keyman Configuration from the input methods menu. Click **Download keyboard**
- [ ] Verify error message "Could not reach Keyman server!" is displayed (This is currently not happening. Bug reported as: https://github.com/keymanapp/keyman/issues/302)
- [x] Close Keyman configuration windows.
- [x] On device, re-enable Internet connectivity
- [x] Activate Keyman and select Keyman Configuration from the input methods menu. Click **Download keyboard**.
- [x] Verify that page displays correctly (should have a **Keyboard Search** box with the prompt: **Enter language or keyboard**.
- [x] Search for Amharic. Should see several keyboards, including some by The Ge'ez Frontier Foundation and some by SIL.
- [x] Double-click any KMP file (in Finder). Should see a “Do you want the Keyman Input Method to install this Package?“ message. If you click Yes, the package should be installed (or updated) and the configuration window should display, showing that the keyboard(s) in the package are installed and enabled. If you click No, the configuration window should not be displayed (but there is a known issue that the very first time after Keyman loads, if the configuration window has not been shown, it will be displayed even if the user clicks No).

### Amharic ###
Select the Amharic keyboard. For each of the following applications/contexts, test that 1) typing **ta** produces **ታ**; 2) typing **t**, left-arrow, **a** produces **አት**; 3) typing **tt**, left-arrow, **a** produces **ታት**; 4) typing **tt**, then mouse-clicking between the two **ታ** characters, and then typing **a** produces **ታት**. 5) typing **at**, then mouse-clicking between the **አ** and **ት** characters, and then typing **a** produces **ዓት**. In each of the last four cases, the insertion point should end up before the final **ት** character. 6) common keyboard shortcuts for the app work as expected. For example: ⌘-F (typically opens a Find dialog or control); ⌘-O (File Open); ⌘-X (Cut); ⌘-C (Copy); ⌘-V (Paste); ⌘-A (Select All). (Note that in Google Docs, these commands correspond to both a Google-Docs command and a browser command. The "normal" behavior in all three browsers is to activate the Google Docs command, not the browser command, with the exception that ⌘-O in Safari opens Safari's standard macOS Open file dialog.) 7) with a few characters displayed, ⌘-A followed by  typing **t** replaces selected characters with **ት**. 8) typing **at**, then ⌘-A, followed by **a** produces **አ**.
- [x] Chrome browser URL bar
- [x] Chrome browser Facebook search control
- [x] Chrome browser Google Docs document (currently known compatibility issue for steps 3, 4 & 5 because any selection change will cause the context to be reset - Google docs can't report context.)
- [x] Chrome browser Word Online _Note: Not using the Office Extension for Chrome - not sure if that would make a difference_
    1. [x] a) Beginning of paragraph (currently known compatibility issues: steps 1, 3, 4 & 5)
    2. [x] b) Elsewhere in paragraph
- [x] Atom editor - test in Snippet editor (currently [known compatibility issue](https://github.com/keymanapp/keyman/issues/177) for steps 3, 4 & 5)
- [x] Safari browser URL bar
- [ ] Safari browser Facebook search control
- [x] Safari browser Google Docs document (currently known compatibility issue for steps 3, 4 & 5 because any selection change will cause the context to be reset - Google docs can't report context.)
- [x] Safari browser Word Online
    1. [x] a) Beginning of paragraph (currently known compatibility issues: steps 1 (intermittent, sometimes results in ትታ), 7 & 8)
    2. [x] b) Elsewhere in paragraph (occasionally steps 4 & 5 deletes a preceding (space?) character, but I haven't figured out when/why. Step 7 is not relevant. Step 8 fails for the same reason it doesn't work at the beginning of the paragraph. There seems to be a certain level of general twitchiness, with extra characters sometimes being displayed - sometimes only briefly - and characters being deleted.)
- [x] Firefox browser URL bar
- [x] Firefox browser Facebook search control
- [x] Firefox browser Google Docs document (currently known compatibility issue for steps 3, 4 & 5 because any selection change will cause the context to be reset - Google docs can't report context.)
- [x] Firefox browser Word Online
    1. [x] a) Beginning of paragraph
    2. [x] b) Elsewhere in paragraph
- [x] Messages app
    1. [x] a) New message with nobody filled in in To: line
    2. [ ] b) New message in existing conversation, such that the message area has grayed out text: "iMessage") (currently known compatibility issue for step 1 if you start with an empty input box. I.e., any sequence that deletes the only character in the editor in an attempt to replace it will leave the editor blank.)
- [x] Notes app
- [x] TextEdit
- [x] Terminal (known compatibility issues: Steps 1 & 3 insert an extra leading space if there are no preceding characters. Step 2 results in $ታት. Skip step 4 - mouse doesn't move insertion point in Terminal. Step 5 can be done using left-arrow instead. Skip steps 7 & 8. If the Terminal window has LOTS of text in it, it won't provide any context, which leads to other compatibility problems.)
- [x] LibreOffice Vanilla (currently known compatibility issue for steps 3, 4 & 5 because any selection change will cause the context to be reset - LibreOffice Vanilla can't report context.).
- [ ] Mail (message body)
- [x] MS Word
- [ ] MS Powerpoint
- [x] Open Office
- [ ] Adobe InDesign ([compatibility issues](keymanapp/keyman: Issue #782) with steps 1-5.)

### ISIS-Devanagari ###
Select the ISIS-Devanagari keyboard. For each of the following applications/contexts, test that 1) typing **jima** produces **जिमा**; 2) typing **ji**, left-arrow, **ma** produces **माजि**; 3) typing **jj**, left-arrow, **i** produces **जिज**; 4) typing **jj**, then mouse-clicking between the two **व** characters, and then typing **i** produces **जिज**. 5) typing **aj**, then mouse-clicking between the **अ** and **ज** characters, and then typing **i** produces **अइज**. In each of the last four cases, the insertion point should end up before the final **ज** character. 6) delete backspaces over a single Unicode character/code point. 7) common keyboard shortcuts for the app work as expected. For example: ⌘-F (typically opens a Find dialog or control); ⌘-O (File Open); ⌘-X (Cut); ⌘-C (Copy); ⌘-V (Paste); ⌘-A (Select All). (Note that in Google Docs, these commands correspond to both a Google-Docs command and a browser command. The "normal" behavior in all three browsers is to activate the Google Docs command, not the browser command, with the exception that ⌘-O in Safari opens Safari's standard macOS Open file dialog.)
- [ ] Chrome browser URL bar
- [ ] Chrome browser Facebook search control
- [ ] Chrome browser Google Docs document (Steps 1, 2 & 4 will fail initially, but after a few keystrokes, will start to work unless you type too fast. Currently known compatibility issue with steps 3 & 5.)
- [ ] Chrome browser Word Online
    1. [ ] a) Beginning of paragraph (Currently known compatibility issue with steps 1-4. There are generally lots of issues with Word in the Chrome)
    2. [ ] b) Elsewhere in paragraph (Step 1 works sporadically; seems to depend on speed of typing, surrounding context, and/or random factors, perhaps on the server. May have gotten worse recently as a result of the Meltdown patch. Step 2 will work, but only if you click left-arrow twice, as the first once makes no visible difference, though it is presumably moving past the "i" character.)
- [ ] Atom editor - test in Snippet editor (currently [known compatibility issue](https://github.com/keymanapp/keyman/issues/177) with steps 1-5, though step 1 does occasionally work.)
- [ ] Safari browser URL bar
- [ ] Safari browser Facebook search control
- [ ] Safari browser Google Docs document (currently known compatibility issue for steps 3 & 4. Steps 1-4 will fail initially, but after a few keystrokes, it will start to work unless you type too fast.)
- [ ] Safari browser Word Online
    1. [ ] a) Beginning of paragraph (currently known compatibility issues with steps 1-2. Step 1 works if there is following text on the line. So does step 2, but you have to click left-arrow twice.)
    2. [ ] b) Elsewhere in paragraph (Step 2 will work, but only if you click left-arrow twice, as the first one makes no visible difference, though it is presumably moving past the "i" character.)
- [ ] Firefox browser URL bar
- [ ] Firefox browser Facebook search control
- [ ] Firefox browser Google Docs document (Steps 1 and 2 will work unless you type too fast.)
- [ ] Firefox browser Word Online
    1. [ ] a) Beginning of paragraph (currently known compatibility issues with step 2)
    2. [ ] b) Elsewhere in paragraph (currently known compatibility issues with step 2)
- [ ] Messages app
- [ ] Notes app
- [ ] TextEdit
- [ ] Terminal (skip step 4 - mouse doesn't move insertion point in Terminal. If the Terminal window has LOTS of text in it, it won't provide any context, which leads to other compatibility problems.)
- [ ] LibreOffice Vanilla (currently known compatibility issue for step 3 and 4 because it can't report context.)
- [ ] Mail (message body)
- [ ] MS Word
- [ ] MS Powerpoint (known compatibility issues - need to investigate more)
- [ ] Open Office
- [ ] Adobe InDesign ([compatibility issues](keymanapp/keyman: Issue #782) with steps 1-5.)

### Special Google Docs/Word Online Compatibility Issues ###
1) Select one or more characters. Using any keyboard, type a single keystroke that is expected to output a single special character (e.g. **t** in Amharic). The resulting character should be displayed but not be selected. 2) Using the Amharic keyboard, type **tt** (should produce **ትት**); select the second **ት** and type **a**. The selected **ት** should be removed, and the first **ት** should be replaced by **ታ**. 3) Using the Amharic keyboard, type **ttttt**. Then shift click (with the mouse) right after the second **ት**. Type **a*. The result should be either **ትትአ** or, even better, **ትታ**.
- [ ] Safari / Google Docs (currently known compatibility issue with step 2: results in ትአ. Upon initial activation, step 1 fails, but will correct itself after a few keystrokes.)
- [ ] Safari / Word Online document (currently known compatibility issues: Step 1 may appear to work (sometimes), but the insertion point disappears and no more typing is possible; a subsequent mouse click or arrow key causes some of the deleted characters to reappear! Step 3 results in ትታትትት)
    1. [ ] a) Beginning of paragraph
    2. [ ] b) Elsewhere in paragraph (currently known compatibility issue: Step 2 results in ታት, with the insertion point between the two characters.)
- [ ] Chrome / Google Docs (currently known compatibility issue with step 2: results in ትአ.)
- [ ] Chrome / Word Online document (currently known compatibility issues: Step 2 deletes both characters, leaving nothing; Step 3 results in ት)
    1. [ ] a) Beginning of paragraph
    2. [ ] b) Elsewhere in paragraph
- [ ] Firefox / Google Docs (currently known compatibility issue with step 2: results in ትአ.)
- [ ] Firefox / Word Online document
    1. [ ] a) Beginning of paragraph
    2. [ ] b) Elsewhere in paragraph

### Keyman IM ###
1. In Keyman, turn on verbose logging.
2. Optionally, in Console filter all messages from the **Keyman** process having the text **Crashlytics**
3. Select a keyboard called **EnglishSpanish** (you could get this from Tom or just create one. Doesn't matter what it does as long as it's named that).
4. Open an editable file in Xcode.
5. Type **Crashlytics force now**
- [ ] With each keystroke, Console messages should indicate that the character is being added to the Easter egg string.
- [ ] When the final **w** is typed, a Console message should indicate: **Forcing crash now!**
- [ ] After some delay (you may have to forcibly shut down and restart Keyman or even restart the computer), the new crash should appear in the console on Fabric.io.

### Keyman Engine ###
1. In Keyman, select a keyboard called **EnglishSpanish** (you could get this from Tom or just create one. Doesn't matter what it does as long as it's named that).
2. Turn on verbose logging. (If it's already on, you'll have to explicitly turn it off and back on.)
2. Optionally, in Console filter all messages from the **Keyman** process having the text **Crashlytics - KME:**
4. Open any app where you can type (into a blank document or whatever).
5. Type **Cr@shlyt!cs crash#KME**
- [ ] With each keystroke, Console messages should indicate that the character is being added to KME's Easter egg string.
- [ ] When the final **w** is typed, a Console message should indicate: **Forcing crash now!**
- [ ] After some delay (you may have to forcibly shut down and restart Keyman or even restart the computer), the new crash should appear in the console on Fabric.io.
 
## OSK UI/Functionality Tests ##
- [x] Verify behavior of "Always show on-screen keyboard" option
- [x] Verify behavior and appearance of On-Screen Keyboard and the menu that toggles it on and off.
- [x] With OSK visible, verify that switching keyboards updates the display to show the appropriate layout.
- [x] Verify that switching to system keyboard or other IM turns off Keyman OSK.

## What's New Tests
- [x] Refer to the new changes in `mac/history.md` and verify functionality

**Comment by mcdurdin** [comment]
Notes:

* In Word online in Chrome, typing ta at start of document results in blank document instead of `ታ`. 
* In Google Docs on Chrome, sometimes, an additional letter is deleted to left of context when you first start editing. But not often.

There is a somewhat consistent problem with the start of a text run. We should be able to trace that and improve outcomes on many of these.

**Comment by mcdurdin** [comment]
Closing this now. Checklist has better results than previous version and no regressions found thus far.
