### ISSUE TITLE
[linux] 13.0 Pre-beta checklist

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyman#2527]
# Keyman for Linux Acceptance Test Procedures #
These test procedures are to be run before any beta or stable build is published.

## Visual Inspection of master/beta branches
- [x] ![Build Status](https://build.palaso.org/app/rest/builds/buildType:(id:KeymanLinux_Master)/statusIcon) Verify latest CI build of [master](https://build.palaso.org/viewType.html?buildTypeId=KeymanLinux_Master) is successful
- [x] Verify `linux/history.md` contains all the current changes

## Gather Assets for Testing ##
- [ ] Ubuntu 18.04 Bionic - VMN or physical okay

## Setup Steps ##
- [ ] Uninstall previous versions of Keyman for Linux on the system

# Keyman for Linux #

## Basic installation ##
- [ ] Add the ppa
```
sudo add-apt-repository ppa:keymanapp/keyman-daily
sudo apt-get update
sudo apt-get install keyman onboard
```
- [ ] From the launcher, start "Keyman Keyboard"
- [ ] Verify "Keyman Configuration" panel appears
- [ ] Click "Download", enter a keyboard to search for, and click the keyboard
- [ ] Click "Install keyboard"
- [ ] If the package includes a readme file, verify that it appears in the install window
- [ ] If the package includes a welcome file, verify that it appears after installation
- [ ] Verify the new keyboard appears in "Keyman Configuration"
- [ ] Add the keyboard to GNOME
    - [ ] From Ubuntu, start "Settings" --> "Region & Language"
    - [ ] In "Input Sources", click "+" to add input source
    - [ ] Search for the language for the new keyboard under "Other"
    - [ ] Click "Add"
    - [ ] Verify the language tag for the current keyboard appears on the top right of the screen (`"en"` for English")
- [ ] Click Windows-spacebar to switch to the newly installed keyboard
- [ ] In a text editor (gedit), verify that the newly installed keyboard can type

## Install a package from disk
- [ ] From the "Keyman Configuration" panel, click "Install"
- [ ] Browse to a local .kmp file on disk and click "Open" to install it
- [ ] If the package includes a readme file, verify that it appears in the install window
- [ ] If the package includes a welcome file, verify that it appears after installation
- [ ] Add the keyboard to GNOME (follow steps above)
- [ ] Click Windows-spacebar to switch to the newly installed keyboard
- [ ] In a text editor, verify that the newly installed keyboard can type

## About keyboard
- [ ] From the "Keyman Configuration" panel, select a keyboard and click "About"
- [ ] Verify package and keyboard information is displayed

## Keyboard help
- [ ] From the "Keyman Configuration" panel, select a keyboard and click "Help"
- [ ] If the package does not include a welcome file verify that the "Help" button is disabled
- [ ] If the package includes a welcome file, verify that it appears.

## On Screen Keyboard tests
- [ ] From the launcher, start "onboard"
- [ ] Verify the OSK for the current keyboard appears at the bottom of the screen
- [ ] Verify that the default OSK (en-US) is shown if the current keyboard doesn't have one
- [ ] Click Windows-spacebar to switch to another keyboard than has an OSK
- [ ] Verify the OSK switches to match the current keyboard
- [ ] In a text editor, verify clicking on an OSK key produces expected output

## On Screen Keyboard configuration
- [ ] From the launcher, start "onboard settings"
- [ ] Verify the "Onboard Preferences" panel appears

## What's New Tests
- [ ] Refer to the new changes in `linux/history.md` and verify functionality

**Comment by darcywong00** [comment]
Passes with 13.0.22 beta
