### ISSUE TITLE
[Android] 13.0 Pre-beta checklist

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyman#2529]
# Keyman for Android Acceptance Test Procedures #

These test procedures are to be run before any beta or stable build is published. Copy these checklists of tests before PRs are merged into the beta and stable branches.

## Visual Inspection of master branch
- [ ] ![Build Status](https://build.palaso.org/app/rest/builds/buildType:(id:KeymanAndroid_Build)/statusIcon) Verify latest CI build of [master](https://build.palaso.org/viewType.html?buildTypeId=KeymanAndroid_Build) is successful 
- [ ] Verify `android/history.md` contains all the current changes

## Gather Assets for Testing ##
- [ ] Physical Android phone (record device's Android -- version 4.4 KitKat or later)
- [ ] External bluetooth keyboard that's paired with the Android device
- [ ] External keyboard (European AZERTY layout with 102nd key)

## Setup Steps ##
- [ ] Uninstall previous version of Keyman on the device (don't forget to reset user settings for the app; in Android Pie: Settings>Storage>Other apps>Keyman>Clear Storage)
- [ ] Install test build APK
- [ ] On device, disable internet connectivity
- [ ] Start Keyman and select **Add a keyboard for your language**
- [ ] Verify error message "Cannot connect to Keyman server!" is displayed
- [ ] Click OK to dismiss.  Close Keyman app
- [ ] On device, enable internet connectivity
- [ ] Start Keyman
- [ ] On initial **Get Started** menu, select "Enable Keyman as system-wide keyboard" and do any necessary system steps to enable Keyman

----

### Get Started ###
- [ ] Verify touching **Add a keyboard for your language** pulls up the **Add New Keyboard** menu
- [ ] Verify touching **Enable Keyman as system-wide keyboard** pulls up system dialog for keyboards
- [ ] Verify **Set Keyman as default keyboard** can be toggled on/off
- [ ] Verify touching **More info** brings up the version page and Keyman Help page
- [ ] Clear **Show 'Get Started' on startup** checkbox, close and re-open Keyman, and verify **Get Started** menu does not appear

### Add New Keyboard ###
This menu is accessed via **Get Started** menu or the Settings button on the OSK
- [ ] On the device, enable internet connectivity
- [ ] Verify a new keyboard can be downloaded and selected
- [ ] On the device, disable internet connectivity
- [ ] Attempt to download another keyboard and verify device immediately displays a msg "No internet connection"
- [ ] On the device, re-enable internet connectivity

### Settings ###
- [ ] Installed Languages ... Add Language
- [ ] Select an installed language ... Add (another) Keyboard
- [ ] Select keyboard settings menu
- [ ] Verify Info appears with keyboard version, help link, and QR code
- [ ] If keyboard update is available, click on version and verify update
- [ ] If help link is available, click on link
- [ ] Select an installed language ... Dictionary
- [ ] Turn on/off 'Enable Predictions' and validate each
- [ ] Turn on/off 'Enable Corrections' and validate each
- [ ] Validate that when both predictions and corrections are off, banner is not visible
- [ ] Add/Remove dictionaries - validate
- [ ] If multiple dictionaries are available, test swapping between them

### Share ###
- [ ] Type and verify text can be shared to external app

### Keyman Browser ###
- [ ] On default page, click on text field and set system keyboard to Keyman
- [ ] Verify can type with Keyman as system keyboard
- [ ] Close and reopen Keyman app

### Text Size ###
- [ ] Verify text can be rescaled from Text Size 16 to 72

### Clear Text ###
- [ ] Verify text can be cleared

### Info ###
- [ ] Verify Keyman Android version briefly appears and record the version
- [ ] Verify Help documentation appears with base URL https://help.keyman.com/

### Install Updates ###
This menu option only appears when a language resource (keyboard or lexical-model) update is available
- [ ] Click on "Install Updates"
- [ ] Accept "Download" on the dialogue
- [ ] Verify resource is updated after background download complete

----

### In-app Keyboards
These tests are run in the context of typing in the Keyman app

#### English(EuroLatin SIL)
- [ ] In portrait orientation, verify OSK is visible and fills the width the bottom of the screen
- [ ] Verify long-press `q` key works
- [ ] Verify long-press `p` key works
- [ ] Verify uppercase layer can be selected via `SHIFT`
- [ ] Verify number layer can be selected via `123`
- [ ] Verify long-press `1` key works
- [ ] Verify long-press `0` key works
- [ ] Verify backspace, space, and enter keys work
- [ ] Verify *Khmer* -> *Khmer Angkor* keyboard can be added via Settings menu
- [ ] Repeat in landscape orientation

#### Non-Latin script Keyboard
- [ ] In the app, add/select a random non-Latin script keyboard
- [ ] Verify OSK is visible
- [ ] Test several keys and modifiers and verify Latin characters are not appearing.

### System Keyboards
These tests are run with Keyman selected as a system keyboard, and in the context of typing in an external app (like Google Keep)

#### English(EuroLatin SIL)
- [ ] In portrait orientation, verify OSK is visible and fills the width the bottom of the screen
- [ ] Verify long-press `q` key works
- [ ] Verify long-press `p` key works
- [ ] Verify uppercase layer can be selected via `SHIFT`
- [ ] Verify number layer can be selected via `123`
- [ ] Verify long-press `1` key works
- [ ] Verify long-press `0` key works
- [ ] Verify backspace, space, and enter keys work
- [ ] Verify can change to random non-Latin script keyboard via globe button
- [ ] Repeat in landscape orientation

#### "Close Keyman" and Switch to next system keyboard
This tests the "CLOSE KEYMAN" button that's only available when Keyman is a system keyboard.
- [ ] Click the globe button
- [ ] Verify the bottom left of the Keyboards picker has a button "CLOSE KEYMAN"
- [ ] Click the "CLOSE KEYMAN" button
- [ ] Verify the Keyman system keyboard is closed
- [ ] Display the OSK and verify the next system keyboard is enabled (e.g Google Gboard)

#### External (Bluetooth) keyboard
This test is run with an external bluetooth keyboard paired to the device
- [ ] Start with English(EuroLatin SIL) as the selected keyboard
- [ ] Verify OSK is not visible
- [ ] Verify can type with numbers, letters, and punctuation
- [ ] Verify `caps lock` has no effect when typing
- [ ] Verify long-press on a character repeats that character
- [ ] Verify `tab` toggles to next field
- [ ] Verify `enter` adds a newline
- [ ] Verify `backspace` removes a character
- [ ] Verify `ctrl` + `tab` brings up the menu to add new keyboard
- [ ] Select a non-Latin keyboard
- [ ] Resume typing and verify new script appears

#### External European AZERTY keyboard
This test is run with an external European AZERTY keyboard paired to the device. It should contain the 102nd key `<>` on the bottom row next to the left-shift.
- [ ] Start Keyman and Install French -> French keyboard
- [ ] From the physical keyboard, type on the top letter row (azerty)
- [ ] Verify `azerty` appears
- [ ] Type on the 102nd key
- [ ] Verify `<` appears
- [ ] Type shift-102nd key
- [ ] Verify `>` appears

----

### KMP distribution
- [ ] Reset app settings (in Android Pie: Settings>Storage>Other apps>Keyman>Clear Storage)
- [ ] Verify kmp [distribution](https://help.keyman.com/developer/10.0/guides/distribute/) successfully installs<br/>
 Example: [Khmer Angkor](https://downloads.keyman.com/keyboards/khmer_angkor/1.0.2/khmer_angkor.kmp)
- [ ] Verify kmp successfully installs from Settings --> Add Keyboard from Device
----

## What's New Tests
- [ ] Refer to the new changes in `android/history.md` and verify functionality

**Comment by darcywong00** [comment]
I've completed these tests. Two outstanding issues:

1. As system keyboard, it intermittently crashes rotating between portrait and landscape view (SIL EuroLatin keyboard, en.nrc.mtnt uninstalled)

2. Physical keyboard connected, Tab key has no effect. Ctrl+Tab combo does work in bringing up keyboard menu

**Comment by darcywong00** [comment]
The two issues found during testing are tracked above
