### ISSUE TITLE
[iOS] 13.0 Pre-beta checklist

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyman#2530]
# Keyman for iPhone and iPad Acceptance Test Procedures #

These test procedures are to be run before any beta or stable build is published. Copy these checklists of tests before PRs are merged into the beta and stable branches.

## Visual Inspection of master branch
- [x] ![Build Status](https://build.palaso.org/app/rest/builds/buildType:(id:Keyman_iOS_Master)/statusIcon) Verify latest CI build of [master](https://build.palaso.org/viewType.html?buildTypeId=Keyman_iOS_Master) is successful
- [x] Verify `ios/history.md` contains all the current changes

## Gather Assets for Testing ##
- [ ] Record device's iOS version 
- [ ] Ensure the device is properly configured for testing and is registered with TestFlight.

At this time, Keyman for iOS does not support external keyboard input.

## Setup Steps ##
- [ ] Uninstall previous version of Keyman on the device
- [ ] Install test build IPA
- [ ] On device, disable internet connectivity
- [ ] Start Keyman and select **Add a keyboard for your language**
- [ ] Verify error message "Could not reach Keyman server!" is displayed
- [ ] Click OK to dismiss.  Close Keyman app
- [ ] On device, enable internet connectivity
- [ ] Start Keyman
- [ ] On initial **Get Started** menu, select "Enable Keyman as system-wide keyboard" and do any necessary system steps to enable Keyman

### Get Started ###
- [ ] Verify touching **Add a keyboard for your language** pulls up the **Add New Keyboard** menu
- [ ] Verify touching **Enable Keyman as system-wide keyboard** pulls up accurate instructions.
- [ ] Verify touching **More info** brings up an accurate version and "Getting Started" page.
- [ ] Set **Don't show again** to checked, close and re-open Keyman, and verify **Get Started** menu does not appear

### Settings ###
- [ ] Installed Languages ... Add Language
- [ ] Select an installed language ... Add (another) Keyboard
- [ ] Select an installed language ... Dictionary
- [ ] Turn on/off 'Enable Predictions' and validate each
- [ ] Turn on/off 'Enable Corrections' and validate each
- [ ] Validate that when both predictions and corrections are off, banner is not visible
- [ ] Add/Remove dictionaries - validate
- [ ] If multiple dictionaries are available, test swapping between them

Note that the stated version will be inaccurate if run within the Simulator instead of on a physical device.

### Add New Keyboard ###
This menu is accessed via **Get Started** menu or **Settings** menu
- [ ] On the device, enable internet connectivity
- [ ] Verify a new keyboard can be downloaded and selected
- [ ] Return to the text input screen and confirm that it operates correctly.
- [ ] Without changing selected language, confirm that it can be cleanly deleted via the Settings menu.
- [ ] Confirm that another keyboard is correctly selected afterward.

### Share ###
- [ ] Type and verify text can be copied and shared to external app

### Keyman Browser ###
- [ ] On default page, click on text field and set system keyboard to Keyman
- [ ] Verify can type with Keyman as system keyboard
- [ ] Close and reopen Keyman app

### Text Size ###
- [ ] Verify text can be rescaled from Text Size 16 to 72

### Clear Text ###
- [ ] Verify text can be cleared

### Info ###
- [ ] Verify that the Keyman IOS version briefly appears and record the version
- [ ] Verify that the Info menu options matches that of the **More Info...** option from the **Get Started** menu option.

## Keyboard Tests

- [ ] Confirm all keyboard tests below have been performed in both portrait and landscape modes.

### **English (Eurolatin2)** in-app
- [ ] In portrait orientation, verify that the OSK appears and fills the width the bottom of the screen
- [ ] Verify long-press `q` key works
- [ ] Verify long-press `p` key works
- [ ] Verify uppercase layer can be selected via `SHIFT`
- [ ] Verify number layer can be selected via `123`
- [ ] Verify long-press `1` key works
- [ ] Verify long-press `0` key works
- [ ] Verify backspace, space, and enter keys work
- [ ] Verify **French: French** keyboard can be added via Settings

Note that the shown EuroLatin2 is a highly customized keyboard explicitly designed for mobile.

### **French: French** in-app
- [ ] Verify that long-press `SHIFT` key works and allows selection of layers.
- [ ] Ensure key inputs from the right-most selectable long-press layer works.
- [ ] Revert to the default layer and ensure basic key inputs work.
- [ ] Use the globe key to access the keyboard menu.
- [ ] From the `Settings > Languages > French > French >` menu, follow the "Help link" and ensure it connects properly to help.keyman.com.
- [ ] Returning to the app, delete the **French: French** keyboard via Settings.

Note that the specified French keyboard lacks a customized keyboard layout for mobile, relying instead upon the default one provided by KeymanWeb.

### Predictive Text
- [ ] **TODO**

## What's New Tests
- [ ] Refer to the new changes in `ios/history.md` and verify functionality

**Comment by jahorton** [comment]
Detected issues:
- [ ] After the app successfully loads the keyboard catalog, disable internet connectivity and _then_ attempt to download a keyboard.
  - This may either crash the app or fail silently.

**Comment by jahorton** [comment]
The remaining issues to be tackled have been documented within their own issues; I'm closing the pre-beta test now.
