### ISSUE TITLE
[Windows] TODO list for Keyman for Windows setup

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyman#3339]
# Keyman for Windows Setup TODO

### Bugs
- [x] crash when missing files for a given tier: https://sentry.keyman.com/organizations/keyman/issues/550/?environment=development&referrer=alert_email
- [x] message from msi appears to be wrong "Removing older versions" only shown.

### Functionality
- [x] Proxy server detection (see https://superuser.com/questions/1179016/how-to-setup-a-local-proxy-server-for-testing-a-program, https://superuser.com/questions/180480/how-to-simulate-corporate-proxy-server-on-my-development-machine for testing suggestions)
- [x] Strip off " (1)" suffix that IE and other browsers add to filenames
- [x] 9. Embed MIT license
- [x] 7. Handling offline scenarios and transitioning to online (e.g. allowing through firewall after prompt; retry needed?)
      - [ ] 16. Need to show 'checking online' dialog as part of this (except in silent mode)
- [x] 17. Allow specification of tier in setup (-t for parameter; keyman-setup-alpha, keyman-setup-beta, keyman-setup[-stable] for embedded).
      - by default, should we use the compiled-in tier? Yes, I think. So we need to make that clear in the installer UI.

- [x] 10. Consider mocks and unit tests

- [x] 15. Review unattended install scenarios, offline, online, etc.

- [x] Consider refactoring install options (e.g. check for updates, start with windows, etc) to only be set if Keyman is installed (or upgraded?).
      In this situation, make it clear in Install Options that these are only available in that case (perhaps indenting under Keyman module install
      checkbox?)

- [x] If no packages are available, and Keyman must be installed, don't show the module options in the Install Options dialog, because there is nothing the user can do with it.

### Documentation
- [x] 13. Update kmcomapi docs
- [x] Update kmshell -i docs and bootstrap docs

# Done

- [X] Ensure that Keyman for Windows setup points to staging-keyman-com rather than keyman.com etc before merging PR.
- [X] 8. Refactor of PackagesOnly vs ShouldInstallKeyman (PackagesOnly is awkward and needs to go)
- [X] Deprecated keyboards will not be impacted by the changes because they will not be part of the bundling strategy -- they will only be available as
      standalone .kmp downloads for the truly desperate! (from https://github.com/keymanapp/keyboards/issues/1277)
- [X] 11. Constants for GUIDs and file extensions etc
- [X] Remove unused code:
  * `IsSameMajorVersion` https://github.com/keymanapp/api.keyman.com/pull/83#discussion_r449410956
- [X] https://downloads.keyman.com/api/version/windows/2.0 is returning "exe" type for .msi files (probably a CI build script issue)
- [X] 12. Refactor dependencies for ResourceDownloader to avoid circular dependencies
- [X] 2. error management and logging (sentry?)
- [X] 1. localised strings (and management)
- [X] setup does not show file sizes in description for "setup will download and install"
- [X] download of assets is saving into local folder instead of temp folder
- [X] 6. Supporting choice of languages during install via command line and executable filename
- [X] bundled installer is not using local version even though it is a higher version number!
- [X] setup is downloading .exe not .msi
- [X] api updates according to allow download of appropriate .exe bundle, .msi, or setup bootstrapper
- [X] keyboard download post install seems to hang the installer: may be pulling from wrong location?
- [X] download seems awfully slow given local network. <-- replace old httpuploader with standard library
- [X] fails to download keyboard with "Unable to contact server"
      * protocol is actually with https regardless of context (should be http for dev)
- [X] missing bcp47 tag causes http://keyman.com.local/keyboards/install/khmer_angkor to fail with:

      PHP Fatal error:  Uncaught TypeError: preg_match() expects parameter 2 to be string, null given in C:\Projects\keyman\sites\keyman.com\keyboards\install.php:86
      Stack trace:
      #0 C:\Projects\keyman\sites\keyman.com\keyboards\install.php(86): preg_match()
      #1 C:\Projects\keyman\sites\keyman.com\keyboards\install.php(51): Keyman\Site\com\keyman\KeyboardInstallPage::validate_tag()
      #2 C:\Projects\keyman\sites\keyman.com\keyboards\install.php(21): Keyman\Site\com\keyman\KeyboardInstallPage::render_keyboard_details()
      #3 {main}
        thrown in C:\Projects\keyman\sites\keyman.com\keyboards\install.php on line 86
- [X] 5. Cleanup of global variable ExtPath, TempPath, ProgramPath (use FInstallInfo)

- [X] Remove `BuildKeyboardDownloadPath $version` parameter https://github.com/keymanapp/api.keyman.com/pull/83#discussion_r449412411 [not removed, it is now in use]

# ~~Future~~

These items are ignored for now. We may consider re-evaluating in the future but not important enough to list as new issues.

- [ ] ~~Download dialog should be integrated into the Setup dialog instead, with
      progress shown there. The downloads should all be done before the install
      starts. Errors in download of optional components should allow install to
      continue.~~
- [ ] ~~? Not as important: downloading an updated setup.exe -- how to handle searching for local packages, passing of command line parameters, etc.~~

### ~~Refactoring~~
- [ ] ~~16. Consolidate big piles of boolean parameters into record (TInstallInfo.Options?)~~

# Other projects

- Online Update Checks in Keyman for Windows: see #3393
- Tidy up all direct references to Keyman websites. We should do this for better integration with staging sites. See #3394
