### ISSUE TITLE
[Windows] Tidy up all direct references to Keyman websites

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyman#3394]
We should do this for better integration with staging sites. These are the ones I found:

27 results - 11 files

windows\src\desktop\kmshell\xml\downloadkeyboard.xsl:
- [x]  `66:           <xsl:attribute name="src">https://keyman.com/go/desktop/10.0/download-keyboards?version=<xsl:value-of select="/Keyman/Version" /></xsl:attribute>&#160;`

windows\src\desktop\kmshell\xml\keyman_keepintouch.xsl:
- [x]  `8:         document.getElementById('keepintouch_frame').src = 'https://keyman.com/go/desktop/10.0/keep-in-touch?embed=1';`

windows\src\desktop\kmshell\xml\keyman_keyboardlist.xsl:
- [x]  `285:                                     <xsl:attribute name="href">keyman:link?url=https://keyman.com/go/keyboard/<xsl:value-of select="../../id" />/share</xsl:attribute>`
- [x]  `291:                                     text: 'https://keyman.com/go/keyboard/<xsl:value-of select="../../id"/>/share',`

windows\src\desktop\kmshell\xml\keyman_support.xsl:
- [x]  `26:             <xsl:with-param name="command">keyman:link?url=https://keyman.com/go/desktop/10.0/forums</xsl:with-param>`
- [x]  `42:             <li><a href="https://www.keyman.com/">www.keyman.com</a></li>`
- [x]  `45:             <li><a href="keyman:link?url=https://keyman.com/go/desktop/10.0/support"><xsl:value-of select="$locale/String[@Id='S_Button_OnlineSupport']"/></a></li>`

windows\src\developer\TIKE\dialogs\UfrmAboutTike.dfm:
- [x]  `526:     Caption = 'http://www.keyman.com/developer/'` (fix: #3618)

windows\src\developer\TIKE\xml\kmw\packages.html:
- [x]  `35:         <a href='https://keyman.com/go/developer/10.0/ios-app' target='_blank' class='install-link'>Install Keyman for iOS</a>` (Fix: #3613)
- [x]  `36:         <a href='https://keyman.com/go/developer/10.0/android-app' target='_blank' class='install-link'>Install Keyman for Android</a>` (Fix: #3613)

windows\src\developer\TIKE\xml\project\distribution.xsl:
- [x]  `14:               <li><a href="https://keyman.com/go/developer/10.0/help-keyboards">Share source and add to Keyman keyboard repositories</a></li>` (fix: #3618)
- [x]  `15:               <li><a href="https://keyman.com/go/developer/10.0/help-packages">Windows and macOS distribution</a></li>` (fix: #3618)
- [x]  `16:               <li><a href="https://keyman.com/go/developer/10.0/help-mobile">iPhone, iPad and Android distribution</a></li>` (fix: #3618)
- [x]  `17:               <li><a href="https://keyman.com/go/developer/10.0/keymanweb">Web soft keyboard</a></li>` (fix: #3618)
- [x]  `18:               <li><a href="https://keyman.com/go/developer/10.0/keyman-engine-home">Keyman Engine</a></li>` (fix: #3618)
- [x]  `33:                 <b>Recommended option!</b> &#160; <a href='https://keyman.com/go/developer/10.0/help-keyboards'>Learn more</a></li>` (fix: #3618)
- [x]  `35:                 <a href='https://keyman.com/go/developer/10.0/help-packages'>Learn more</a></li>` (fix: #3618)
- [x]  `37:                 <a href='https://keyman.com/go/developer/10.0/help-mobile'>Learn more</a></li>` (fix: #3618)
- [x]  `39:                 <a href='https://keyman.com/go/developer/10.0/keymanweb'>Learn more</a></li>` (fix: #3618)
- [x]  `42:           <p>You can also create your own custom keyboarding product based on Keyman: <a href='https://keyman.com/go/developer/10.0/keyman-engine-home'>Learn more</a></p>` (fix: #3618)

windows\src\developer\TIKE\xml\project\globalwelcome.xsl:
- [x]  `17:               <p id='header-link'><a target='_blank' href='https://keyman.com/go/developer/12.0/home'>https://keyman.com/developer/</a></p>` (fix: #3618)

windows\src\developer\TIKE\xml\project\keyboards.xsl:
- [x]  `48:             It's a good idea to read <a href='https://keyman.com/go/developer/10.0/help-keyboards'>Developing Open Source Keyboards</a> for guidelines` (fix: #3618)

windows\src\engine\tsysinfo\UfrmAbout.dfm:
- [x]  `45:     Caption = 'https://www.keyman.com/'` (fix: #3619)

windows\src\engine\tsysinfo\UfrmEmail.dfm:
- [x]  `60:     Caption = 'This report will be sent to https://api.keyman.com/'` (fix: #3619)
- [x]  `117:     Hint = 'http://www.keyman.com/privacy'` (fix: #3619)
