### ISSUE TITLE
Full, robust implementation of KMW-based chirality

### ISSUE THREAD

**Issue by jahorton** [keymanapp/keyman#340]
Now that #300 has been pushed through, KMW now has support for modifier chirality.  

The following list was on #300 and should serve as a good checklist for related issues to be resolved before 10.0 goes stable.  (Or beta?)

### Remaining to-dos:

- [ ] Solid cross-platform compatibility testing.  Mobile devices with external keyboards may be particularly in question.  (See #606.)
- [x] New chirality-related API should be properly documented on [help.keyman.com](https://github.com/sillsdev/keyman-help.keyman.com/pull/106).
- [x] The SpecialOSK font lacks `*LALT*`, `*RALT*`, etc keycaps for keyboards with chiral information.
- [x] Mobile presently lacks extensive default chiral-oriented layout structure. (Done in PR #452.)
  * Mobile also lacks state keys (like CAPS LOCK) in its default layout.
  * We merely need to decide on what structure should be default, as the system adapts quite well when adding new subkeys for mobile chiral layers.
  * So far, only variants of the base modifiers (unpaired) have been added; these are in need of font support as noted above.
    * This leaves the bootstrapping chirality.js keyboard without full OSK access when used for testing on Android; not all of its layers have corresponding defaults in kmwlayout.js.
- [x] Embedded integration with KMEA is being done in PR #341.
- [x] Keyman Developer:  compiler integration was completed with PR #313.
- [x] Keyman Developer:  visual editor integration has PR #342.
