### ISSUE TITLE
[Web] Core refactoring

### ISSUE THREAD

**Issue by jahorton** [keymanapp/keyman#349]
Part of our targeted goals for KMW 10.0: 

* [x] Rework the `KeymanWeb` (case-sensitive) global variable.
    - We need to preserve it for compatibility with the existing keyboard interface API; said API should become the _only_ accessible functionality through this object.
    - [x] Will need to check the results' compatibility with the CJK (pick-list) and EuroLatin 2 keyboards.
* [x] The core `keymanweb` object should contain wrapper functions to the API with higher-quality names.
    - E.g, `KeymanWeb.KI()` should be wrapped by `keyman.`_`submodule`_`.index()`.
    - [x] The appropriate _`submodule`_'s name is yet TBD.
* [x] Our original top-level namespace-like structure is no longer appropriately named.  
    - Change the `tavultesoft.keymanweb` object to simply `keyman`.

The above points are all addressed by https://github.com/keymanapp/keyman/pull/356.

Side-effects:
* The following projects will need individualized adjustments to match the new structure:
    - [x] Keyman Developer (Addressed by #386)
    - [x] Keyman for Android (Addressed by #392)
    - [x] Keyman for iPhone and iPad (Addressed by #391)
    - [x] keymanweb.com (Addressed by https://github.com/sillsdev/keyman-keymanweb.com/pull/23.)
    - [x] The Bookmarklet feature (Addressed by https://github.com/sillsdev/keyman-r.keymanweb.com/pull/17.)
    - [x] Correlated changes may be needed on our other sites - investigate and fix.
        - [ ] We have an intro-ish section on keyman.com at https://keyman.com/developer/keymanweb/ that will need adjustment when the feature reaches stable.  There's only one version of the page, though, so... a decision needs to be made  on how to handle this.
        - Moved to https://github.com/sillsdev/keyman-keyman.com/issues/53.
* [x] help.keyman.com's KMW 10.0 reference section - update to detail the new API referencing structure!
    - Addressed by https://github.com/sillsdev/keyman-help.keyman.com/pull/114.

**Comment by jahorton** [comment]
All staging work has been merged, and the last remaining point (for the keyman.com website) has been moved to sillsdev/keyman-keyman.com#53.
