### ISSUE TITLE
[Web] KeymanWeb Testing Infrastructure

### ISSUE THREAD

**Issue by jahorton** [keymanapp/keyman#350]
* [x] A: Refactor the web/samples subfolder, moving the appropriate pages to a new web/testing subfolder.  Is being addressed with #353.
* [x] B: Provide necessary infrastructure to support Node.js - in particular, the Mocha package - within the web subfolder.  (Addressed with the base TypeScript conversion PR - #496.)
    - [x] Include changes to .gitignore; the node_packages folder should be listed there.
* [ ] C: Design and implement Mocha-based unit tests for KeymanWeb code coverage.  (See #563.)
    - [ ] Implement these within their own specific subfolder.
    - [ ] Investigate integrating these tests as part of our PR builds.

----

At present, outside of detecting the status of builds, we lack automated testing for KMW.  Our goal is to implement automated tests using [Mocha](https://mochajs.org/), which itself relies upon [Node.js](https://nodejs.org/en/) in order to better ensure build quality into the future.

In the meantime, all of our existing test infrastructure exists within the web/samples subfolder - this should be reorganized to provide a separate web/testing section.
