### ISSUE TITLE
[Windows] Omnibus TODO list for completing Windows language profile installation changes

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyman#3512]
# Things to fix quickly (either LHF or important for testing):

- [x] Remove StockEditor (no longer used) - (done: #3516)

- [x] REFRESH THE KMSHELL UI MAN! (#3178) This is seriously annoying for testing... (done: #3517)

# Next step important tasks

- [x] Deal with split user for Keyman install-time scenarios (bundled installer) -- de-elevate for install of user tip after elevated registration. (done: #3520)

- [x] +  // TODO: the split between user and lm here is a real pain; we need to handle this cleanly (done: #3520)

- [x] Add language selection during installation of keyboard (except when doing a bundled install) (#1456) (done: #3524)
  ` // TODO: let user choose language `
  ` // TODO: allow user to select language `

- [x] Loading keyboard profiles is a little inefficient and may cause stumbling: for example, we register "fr" for sil_euro_latin, but Windows comes back with "fr-FR" in its installed list, so we don't match it. We should instead load the list of installed profiles from Control Panel\International\User Profile and then match up with our known list, and use the BCP47 tag from Windows as the official tag if present (This needs to be done where `keymankeyboardlanguageinstalled` calls `IsTIPInstalledForCurrentUser`). (Can we improve our canonical tag algorithm to handle fr->fr-FR, km-KH->km etc?) (done: #3542)

- [x] Allow other canonical tag formats, e.g. `en-US-fonipa` for keyboard associations (don't be so hard and fast!). (done: #3545)

- [x] add transient profile support to keyman32 (done: #3539)

- [x] fix issues with profile uninstall (done: #3543)

- [x] ~~Merge SuggestedLanguages with Registered profiles (they have essentially the same meaning); for transient langs, use `LangID=0` (leave it out of registry)~~ (not doing this because there are numerous references to the registered profile stuff and the cost outweighs the benefit)

- [x] Fixup registrations etc when upgrading from 13.0 and earlier versions (14.0 alpha upgrades are not a supported scenario) (done: #3552):

       Current User steps:
       * take a list of all HKLM registered keyboards with Enabled=1

       Local Machine steps:
       * register all suggested languages with a langid
       * register the 4 transient language codes
       * modify all registrations to enabled=0 on HKLM (re-register safest?)
       * register any custom-registered keyboards from first current user step

       Current User steps:
       * install each active TIP with InstallLayoutOrTip (and Set-WinUserLanguageList as required)
       * query: any other registry changes required?

- [x] Add Language dialog had some confusion in the list of languages available (done: #3557)

- [x] Add Language doesn't show good names (should use the Langtags.json) (done: #3557)`

- [x] transient language codes not listed in keyboard's installed languages yet in Keyman Configuration

- [x] ar-QA shown instead of Arabic (Qatar) in Keyman Configuration (done: #3558)
- [x] FKeyboardLanguage := TKeymanKeyboardLanguageInstalled.Create(Context, FOwner, BCP47Tag, BCP47Tag, LangID, FGUID, BCP47Tag); // TODO: get language name (done: #3558)

# Final cleanup 

- [x] Remove commented code

- [x] +  // TODO: handle when not enough parameters

- [x] ~~+  // TODO: change LangID to Winapi.Windows.LANGID~~ (not doing this because of interface prototypes)

- [x] Documentation of COM API changes (done: https://github.com/keymanapp/help.keyman.com/pull/211)

- [x] Error management in InstallTip and RegisterTip (TIPMaintenance, kmshell) (done: #3558)
  +  // TODO: handle errors
  +  // TODO: handle errors

- [x] Check that Keyman never uses ItfInputProcessorProfileMgr in COM API for reading state (due to Windows race conditions). Instead read directly from registry. **Result**: this appears to be okay. We read the keys for providing the language list but never for changing state.

- [x] Look at how Keyman checks for corrupted profiles and update that code if necessary (TKeyboardTIPCheck.CheckKeyboardTIPInstallStatus) (done: #3559)

# Additional functionality or refactoring for the future

- [ ] Add back support for disabling keyboards by using `InstallLayoutOrTip`, and keeping a list of 'disabled' profiles in cu registry for future enabling. This does involve the whole merry-go-round for transient langids though.
    * Fixup Load/Unload of keyboards in Keyman Configuration UI
    * This would be helped by changing the mode of Keyman Configuration to instant-change as documented elsewhere. (Issue: #3560)

- [ ] Support transient language profiles in upgrade (Issue: #3561)
- [ ] Support disabled keyboards in upgrade (Issue: #3561)

- [ ] ~~Always do InstallLayoutOrTip and RegisterProfile in a separate process, even if elevation is not required, to avoid Windows race condition bugs with language installation status.~~ Leaving this, unless we encounter edge case bugs in testing.

- [ ] Keyboards are always enabled; if the user selects a Keyman keyboard when Keyman is not running, the TIP attempts to start Keyman, and if it can't, prompts the user to start Keyman. (Issue: #3562)

- [ ] +  // TODO: preserve user language choice with keyboard upgrade (use ForceInstall) (part of online update check) (Issue: #3563)

- [ ] ~~+  // TODO: refactor this to translate legacy data to BCP47 ID and then run~~ this can remain as a lowpri todo in the code

- [ ] ~~Do de-elevated tip install whenever we are elevated? (always assume installation for Explorer-login user, even if running kmshell elevated). Consider adding a helper program to Engine that has the job of being a proxy stub for calling in to kmcomapi?~~ This would be nice to have, but not necessary for our use cases, only for external code, with no evidence of use at this time.

- [ ] Add some unit tests for the TKP* processes (involves TRegistry stub) (Issue: #3564, future)

**Comment by mcdurdin** [comment]
All items now either PRs or new issues. Yay
