### ISSUE TITLE
chore(android/engine): Remove use of lexical-model catalog

### ISSUE THREAD

**Issue by darcywong00** [keymanapp/keyman#3777]
This a change from 13.0 to 14.0 where we no longer need to cache the catalog info of available lexical-models
e.g. https://api.keyman.com/model?q

During keyboard installation, a check is already made for the associated lexical model and that gets downloaded/installed as needed.

### TODO
- [ ] Remove queries for the catalog info
- [ ] Add a one-time upgrade check going to 14.0 for existing keyboards and installing associated lexical-models.
- [ ] Cleanup data/Dataset

@mcdurdin can you provide guidance on impacted UX?
1. in "Settings" --> "Languages", there's existing workflow where users can navigate to "Dictionaries" and pick an available model to install (if not installed yet)
2. I believe we will still allow users to navigate to an installed model and display the model info screen

**Comment by mcdurdin** [comment]
> 1. in "Settings" --> "Languages", there's existing workflow where users can navigate to "Dictionaries" and pick an available model to install (if not installed yet)

When they open the Dictionaries option, Keyman should query api.keyman.com for available models for that language. That can be a synchronous action -- they have to wait for the query to complete to list the available models (or they can click Back to cancel the query). Cleanest way to do this is to show a spinner in the dictionary list until it finishes loading.

If offline, it will show just the installed dictionaries. 

> 2\. I believe we will still allow users to navigate to an installed model and display the model info screen

Yes.

**Comment by darcywong00** [comment]
Too late for 14.0 so this will push to 15.0

**Comment by darcywong00** [comment]
Technical debt we'll try to do as a stretch-goal late in 15.0

**Comment by darcywong00** [comment]
Too much technical debt to get into 15.0 so deferring to 16.0

**Comment by darcywong00** [comment]
Alas, this might be too complicated to get into 16.0 at this point :/

**Comment by mcdurdin** [comment]
> Alas, this might be too complicated to get into 16.0 at this point :/

We've bumped this for 14 and 15, so I think we need to look at this for 16. Happy to rubber ducky with you next week?

**Comment by darcywong00** [comment]
> Happy to rubber ducky with you next week?

I'll be out that week, but can rubber ducky A16S13

**Comment by mcdurdin** [comment]
Sadly bumped again due to work on longpress menus which was higher priority.

**Comment by darcywong00** [comment]
From A18S14 sprint plan, this major refactoring will defer to 19.0
