### ISSUE TITLE
meta: improving our 'good first issue' support

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyman#3882]
There are a bunch of Keyman issues that many people could contribute to.

We need to:

- [ ] Label some appropriate issues
- [ ] Improve our root-level documentation (CONTRIBUTING.md, README.md)
- [ ] Update keyman.com/about/get-involved to point to https://github.com/keymanapp/keyman/contribute

Some locations for good-first-issue labels and adding Keyman:
* https://github.com/deepsourcelabs/good-first-issue#adding-a-new-project
* https://github.com/MunGell/awesome-for-beginners

**Comment by ermshiperete** [comment]
See also #2956
