### ISSUE TITLE
feat(developer): Keyman Core integration with debugger 🐞

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyman#5013]
This is a holding issue for the Keyman Core integration for Developer. We'll be filling this in as we complete planning and design.

**Objective:** 

1. replace existing keystroke debugger with: integration with a standalone version of Keyman Core (not part of Keyman for Windows), and add debugging hooks to Keyman Core to support this.
2. replace existing OSK keyboard import which currently relies on keyman32 with: integration with a standalone version of Keyman Core (not part of Keyman for Windows).

Possible stopgap (or stepping stone): copy existing keyman32 and strip it back to what is required to run standalone in Keyman Developer. 

---

**Keyman Developer:**
 - OS: Windows 
 - Keyman version: target 15.0

**Comment by mcdurdin** [comment]
To do emerging from #5513:

- [ ] Keyboard options
- [ ] Regression testing
- [ ] User-selected base layout
- [ ] Test mode does not work -- do we even need to keep it?
- [ ] Refactor ForceKeyboard property in UfrmDebug.pas
- [ ] Ensure Action_Char and Action_Deadkey have same method of inserting text
- [ ] Ensure insertion point position is tracked correctly during single-step debugging
- [ ] Define behaviour around selection (in DebugEvent.pas)
- [ ] Hide Debug Events form
- [ ] `// TODO: remove +1 -1 messes for deadkey codes //GetDeadkeyMarker(i);` in UfrmDebug.pas
- [ ] `// TODO: this method of inserting chars differs from Action_Char;` in UfrmDebug.pas

**Comment by mcdurdin** [comment]
# User Testing

This is a test on the latest alpha release, as there are multiple PRs that have all merged to master that relate to the Debugger.

* TEST_INSTALL: install and start the debugger

  1. Install Keyman Developer latest alpha
  2. Open any (desktop) keyboard project, load the .kmn, then press F5.
  3. The debugger should start with no errors.

* TEST_RULE_SIMPLE: with khmer_angkor, test the <kbd>x</kbd> key generates ខ

  1. Start the keyboard debugger, press <kbd>x</kbd>

* TEST_RULE_COMPLEX: with khmer_angkor, test that <kbd>x</kbd><kbd>SHIFT</kbd>+<kbd>E</kbd><kbd>j</kbd><kbd>m</kbd><kbd>r</kbd> generates ខ្មែរ.

  1. In the debugger, type <kbd>x</kbd><kbd>SHIFT</kbd>+<kbd>E</kbd><kbd>j</kbd><kbd>m</kbd><kbd>r</kbd>.
  2. Verify that the final chars are `U+1781 U+17D2 U+1798 U+17C2 U+179A`

* TEST_RULE_DEADKEY: with galaxie_greek_mnemonic, test deadkey rules

  1. In the debugger, type <kbd>=</kbd>
  2. The deadkey should be shown in the debug character grid.
  3. Type <kbd>q</kbd>. `q` should be emitted.

* TEST_EDITING: with any keyboard, try various editing tests

  1. Type a variety of strings, then try selecting text, deleting text, copy/paste, and interactions with typing new strings. Make sure that every edit operation is consistent with your expectations. Document any discrepancies.

* TEST_SINGLE_STEP: enable single step (`>>` button) and step through a keystroke event

  1. In khmer_angkor, type <kbd>x</kbd><kbd>SHIFT</kbd>+<kbd>E</kbd><kbd>j</kbd>
  2. Enable single step `>>` button.
  3. Type <kbd>m</kbd>, and use the `>` step button to step through each rule in the keyboard that is matched. Ensure that the stepping makes sense.

* TEST_BREAKPOINT: Test that a breakpoint is hit

  1. In khmer_angkor, add a breakpoint on line 289 (`U+17C1 U+17B6 > U+17C4`) by clicking to left of the line number in the editor. Make sure single step is _disabled_.
  2. Start debugging, type <kbd>x</kbd><kbd>e</kbd><kbd>a</kbd>
  3. The debugger should stop on line 289, allowing you to debug it.

* TEST_DEBUG_STATUS: Verify the contents of the debug status windows

  1. In interactive step-by-step debugging, watch the details shown in the debug status windows to the left of the debug window. Verify that the details match expectations and document discrepancies.

**Comment by MakaraSok** [comment]
| Notes |
| --- |
| Tested with Keyman and Keyman Developer 15.0.105-alpha on Windows 10 Pro 20H2 VM |

- **TEST_INSTALL: FAILED** System Error. Code: 126.

  An error occurs after pressing <kbd>F5</kbd>. Here is the message:
  <img width="139" alt="image" src="https://user-images.githubusercontent.com/28331388/131296586-846f8238-7085-41c9-8b74-5f9ab00ae5a2.png">
  After clicking the OK button on the message, Keyman Developer crashes. Here is the details:
  ```
  Details for error report for Keyman app:
  Application Identifier: tike-15.0.105-alpha
  Error Identifier: 7A7130D013B54A97EC3209A5FD3F35F3
  ```
  The following tests are blocked because the debugger cannot be started in the first place.

- **TEST_RULE_SIMPLE: BLOCKED**
- **TEST_RULE_COMPLEX: BLOCKED**
- **TEST_RULE_DEADKEY: BLOCKED**
- **TEST_EDITING: BLOCKED**
- **TEST_SINGLE_STEP: BLOCKED**
- **TEST_BREAKPOINT: BLOCKED**
- **TEST_DEBUG_STATUS: BLOCKED**

**Comment by MakaraSok** [comment]
cf issue: https://github.com/keymanapp/keyman/issues/5648.

**Comment by mcdurdin** [comment]
@MakaraSok please re-test with latest build from #5697.

@keymanapp-test-bot retest

**Comment by mcdurdin** [comment]
Moving remaining functionality to 16.0.

**Comment by mcdurdin** [comment]
Reopening to review user test and incomplete checklist items

**Comment by MakaraSok** [comment]
* **TEST_INSTALL: PASSED** No error experienced.
* **TEST_RULE_SIMPLE: PASSED** No error experienced.
* **TEST_RULE_COMPLEX: PASSED** No error experienced.
* **TEST_RULE_DEADKEY: PASSED** No error experienced.
* **TEST_EDITING: PASSED** No error experienced.
* **TEST_SINGLE_STEP: PASSED** No error experienced.
* **TEST_BREAKPOINT: PASSED** no issue with editing, but there is a graphic issue with the mouse pounter when hover over the line number. The pointer is shown double.
    <img width="280" alt="image" src="https://user-images.githubusercontent.com/28331388/150497095-a8184811-b26e-4ce0-a779-e2a0f0137b46.png">

* **TEST_DEBUG_STATUS: PASSED** No issue experienced.

**Comment by mcdurdin** [comment]
Thank you for testing @MakaraSok. I will go ahead and close this issue. Additional work is captured in #5898.

> * but there is a graphic issue with the mouse pounter when hover over the line number. The pointer is shown double.

I am inclined to think this is a VM issue rather than an issue in Keyman Developer. If this continues to happen after rebooting your VM, then perhaps we can open a separate issue -- though it is minor.
