### ISSUE TITLE
chore: move directories

### ISSUE THREAD

**Issue by ermshiperete** [keymanapp/keyman#5816]
We want to rearrange a few parts of the repo. Some of the reorg points are:

* Core:
  - [x] move `common/core/web` to `common/web` #6628
  - [x] move `common/core/desktop` to `core` #6629

* Windows/Developer:
  - [x] move `developer/js` to `developer/src/kmlmc` #6630
  - [x] move `windows/src/developer` to `developer/src` #6642

* Following reorgs are huge so we will do them piece by piece:
  - [x] move `windows/src/global` to `common/windows`, `common/windows/delphi`
  - [x] move `windows/src/buildtools` to `common/windows/tools` and `windows/tools` as needed
  - [x] move `windows/src/ext` to `common/windows/delphi/ext`
  - Move `windows/src/desktop` to `windows/src/app` (see #6833)

* Finally, we will split the Windows and Developer builds entirely, which will involve new TeamCity build configurations for Developer. 
  - [x] split Windows and Developer builds #6641
  - Tidy up Makefile headers for Developer and Windows (https://github.com/keymanapp/keyman/pull/6641#discussion_r896290489, https://github.com/keymanapp/keyman/pull/6736#discussion_r897012117, https://github.com/keymanapp/keyman/pull/6720#discussion_r897453618) --> see #6868

* Other chores:
  - Consolidate multiple crc32.cpp (https://github.com/keymanapp/keyman/pull/6747) --> see #6833
  - Consolidate multiple VKScanCodes.cpp ((https://github.com/keymanapp/keyman/pull/6747) --> see #6833

* See also archived discussion doc: https://docs.google.com/document/d/1gWlgDA_re33i_ny4FiBrjuZLJLBJqlIAbspRxI55FQk/edit#heading=h.gvz7zega9tlw

**Comment by darcywong00** [comment]
Part of spec: The Great Filesystem Migration (Issue TBD)

**Comment by mcdurdin** [comment]
Another one: if we can cleanup localization folders for iOS, that would be a great bonus -- it's a mess at present
![image](https://user-images.githubusercontent.com/4498365/155657864-80f90bab-ebd4-4819-993a-4f9afe97c632.png)

**Comment by mcdurdin** [comment]
See also #5815
