### ISSUE TITLE
test(mac): Keyman for Mac 15.0 beta acceptance test

### ISSUE THREAD

**Issue by sgschantz** [keymanapp/keyman#6203]
## Visual Inspection of master branch
- [x] ![Build Status](https://build.palaso.org/app/rest/builds/buildType:(id:Keyman_iOS_Master)/statusIcon) Verify latest CI build of [master](https://build.palaso.org/viewType.html?buildTypeId=KeymanMac_Master) is successful

- [ ] Verify `mac/history.md` contains all the current changes

## Setup Steps ##
- [x] Ensure the device is running the latest version of macOS

- [x] Uninstall previous version of Keyman on the device

- [x] Install latest master build (or whatever version is to be tested) of Keyman on the device

## Basic smoke test ##
- [x] Verify that the version displayed in the About box is correct.

- [x] On device, turn Wifi off and/or disconnect Ethernet cable

- [x] Activate Keyman and select Keyman Configuration from the input methods menu. Click **Download keyboard**

- [ ] Verify error message "Could not reach Keyman server!" is displayed (This is currently not happening. Bug reported as: https://github.com/keymanapp/keyman/issues/302)

- [x] Close Keyman configuration windows.

- [x] On device, re-enable Internet connectivity

- [x] Activate Keyman and select Keyman Configuration from the input methods menu. Click **Download keyboard**.

- [x] Verify that page displays correctly (should have a **Keyboard Search** box with the prompt: **Enter language or keyboard**.

- [x] Search for Amharic. Should see several keyboards, including some by The Ge'ez Frontier Foundation and some by SIL.

- [x] Double-click any KMP file (in Finder). Should see a “Do you want the Keyman Input Method to install this Package?“ message. If you click Yes, the package should be installed (or updated) and the configuration window should display, showing that the keyboard(s) in the package are installed and enabled. If you click No, the configuration window should not be displayed (but there is a known issue that the very first time after Keyman loads, if the configuration window has not been shown, it will be displayed even if the user clicks No).

### Amharic ###
Select the Amharic keyboard. For each of the following applications/contexts, test that 

  1) typing **ta** produces **ታ**;
  2) typing **t**, left-arrow, **a** produces **አት**;
  3) typing **tt**, left-arrow, **a** produces **ታት**;
  4) typing **tt**, then mouse-clicking between the two **ታ** characters, and then typing **a** produces **ታት**.
  
     In each of the last three cases, the insertion point should end up before the final **ት** character. 
  
  6) common keyboard shortcuts for the app work as expected. For example: ⌘-F (typically opens a Find dialog or control); ⌘-O (File Open); ⌘-X (Cut); ⌘-C (Copy); ⌘-V (Paste); ⌘-A (Select All). (Note that in Google Docs, these commands correspond to both a Google-Docs command and a browser command. The "normal" behavior in all three browsers is to activate the Google Docs command, not the browser command, with the exception that ⌘-O in Safari opens Safari's standard macOS Open file dialog.)

  7) with a few characters displayed, ⌘-A followed by  typing **t** replaces selected characters with **ት**.
  8) typing **at**, then ⌘-A, followed by **a** produces **አ**.

- [x] Chrome browser URL bar

- [ ] Chrome browser Facebook search control

- [x] Chrome browser Google Docs document (currently known compatibility issue for steps 3, 4 & 5 because any selection change will cause the context to be reset - Google docs can't report context.)

- [ ] Chrome browser Word Online _Note: Not using the Office Extension for Chrome - not sure if that would make a difference_
    1. [ ] a) Beginning of paragraph (currently [known compatibility issues](https://github.com/keymanapp/keyman/issues/3970) steps 1, 3, 4 & 5)
    2. [ ] b) Elsewhere in paragraph

- [x] Atom editor - test in Snippet editor (currently known compatibility issue for steps 3, 4 & 5)

- [x] Safari browser URL bar

- [ ] Safari browser Facebook search control

- [ ] Safari browser Google Docs document (currently known compatibility issue for steps 3, 4 & 5 because any selection change will cause the context to be reset - Google docs can't report context.)

- [ ] Safari browser Word Online
    1. [ ] a) Beginning of paragraph (currently [known compatibility issues](https://github.com/keymanapp/keyman/issues/3970) steps 1, 3, 4 & 5, 7&8)
    2. [ ] b) Elsewhere in paragraph (occasionally steps 4 & 5 deletes a preceding (space?) character, but I haven't figured out when/why. Step 7 is not relevant. Step 8 fails for the same reason it doesn't work at the beginning of the paragraph. There seems to be a certain level of general twitchiness, with extra characters sometimes being displayed - sometimes only briefly - and characters being deleted.)

- [x] Firefox browser URL bar

- [ ] Firefox browser Facebook search control

- [x] Firefox browser Google Docs document (currently known compatibility issue for steps 3, 4 & 5 because any selection change will cause the context to be reset - Google docs can't report context.)

- [ ] Firefox browser Word Online
    1. [ ] a) Beginning of paragraph
    2. [ ] b) Elsewhere in paragraph

- [x] Messages app
    1. [x] a) New message with nobody filled in in To: line
    2. [ ] b) New message in existing conversation, such that the message area has grayed out text: "iMessage") 

- [x] Notes app

- [x] TextEdit

- [x] Terminal (known compatibility issues: Steps 1 & 3 insert an extra leading space if there are no preceding characters.  Skip step 4 - mouse doesn't move insertion point in Terminal. Step 5 can be done using left-arrow instead. Skip steps 7 & 8. If the Terminal window has LOTS of text in it, it won't provide any context, which leads to other compatibility problems.)

- [ ] LibreOffice 7.0 (currently [known compatibility issue](https://github.com/keymanapp/keyman/issues/175) for steps 3, 4 & 5 because any selection change will cause the context to be reset - LibreOffice Vanilla can't report context.).

- [ ] Mail (message body)

- [ ] MS Word

- [ ] MS Powerpoint (see #687 for compat issue)

- [ ] Adobe InDesign ([compatibility issues](keymanapp/keyman: Issue #782) with steps 1-5.)

## Optional test of Sentry error reporting ##
1. In Keyman, turn on verbose logging.
2. Optionally, in Console filter all messages from the **Keyman** process having the text **Sentry**
3. Select a keyboard called **EnglishSpanish** (see /mac/test/EnglishSpanish folder in the source repo)
4. Open an editable file in Xcode.
5. Type **Sentry force now**
- [x] With each keystroke, Console messages should indicate that the character is being added to the Easter egg string.
- [x] When the final **w** is typed, a Console message should indicate: **Forcing crash now!**
- [x] After some delay (you may need to switch Keyman off and on again), the new crash should appear in the console on sentry.keyman.com.
 
## OSK UI/Functionality Tests ##
- [x] Verify behavior of "Always show on-screen keyboard" option
- [x] Verify behavior and appearance of On-Screen Keyboard and the menu that toggles it on and off.
- [x] With OSK visible, verify that switching keyboards updates the display to show the appropriate layout.
- [x] Verify that switching to system keyboard or other IM turns off Keyman OSK.

## What's New Tests
- [ ] Refer to the new changes in `HISTORY.md` and verify functionality; add checkboxes here for each point

**Comment by mcdurdin** [comment]
See https://github.com/keymanapp/keyman/issues/3973 for 14.0

**Comment by sgschantz** [comment]
For Amharic testing, Apple apps Notes, TextEdit, Safari, Messages, Numbers and Pages all function as expected.
Non-Apple apps Chrome, Google Docs, Atom and Firefox all fail for almost every test.
Slack and Signal pass all Amharic tests, except #7.
WhatsApp passes all Amharic tests.

**Comment by sgschantz** [comment]
The thing in common betwen all apps failing the Amharic tests is that there is hard-coded check for each of them [here](https://github.com/keymanapp/keyman/blob/master/mac/Keyman4MacIM/Keyman4MacIM/KMInputMethodEventHandler.m).  When commenting out the hard-coded check for vscode, it goes from failing all Amharic tests but one to passing all except #2 and #7.

Here is the comment from the code about the hard-coding:
```
TODO: Pages and Keynote (and possibly lots of other undiscovered apps that are otherwise compliant
with Apple's IM framework) have a problem in that if the user selects a different font (or other
formatting) and then types a sequence that causes characters to be added to the document and then
subsequently replaced, the replacement causes the formatting decision to be forgotten. This can be
"fixed" by treating them as legacy apps, but it causes other problems.
```

I have not yet been able to reproduce the problem described that this hard-coding is helping to avoid.

**Comment by mcdurdin** [comment]
I am wondering if there is a permission missing for Keyman. Both Privacy / Input Monitoring and Privacy / Accessibility need to be enabled. Sometimes Keyman is missing from one of those but can be manually added:

* Click the `[+]` button, then press <kbd>Command</kbd>+<kbd>Shift</kbd>+<kbd>G</kbd>.
* Type `~/Library/Input Methods` and press <kbd>Return</kbd>.
* Keyman should appear in the folder.

Another thing to [try](https://help.keyman.com/knowledge-base/104) is:

`sudo tccutil reset postevent`

(This is needed because it looks like macOS adds an app that fails a permission to an internal list and automatically re-fails it on subsequent attempts.)

**Comment by sgschantz** [comment]
The tccutil reset addressed most issues with Amharic. However, I had to do the reset on Keyman rather than postevent which gave an error. Why would we specify postevent?

I entered: `tccutil reset All keyman.inputmethod.Keyman`

I don't understand the tradeoff regarding the hard-coded fix for non-Apple apps. Here is another description from issue [#991](https://github.com/keymanapp/keyman/issues/991): `Probably the answer is to revert that change and not treat those apps as legacy. That would mean that you'd be back to the problem of not being able to choose a font (or other formatting) and then start typing. You'd have to have at least one character typed select it, and then apply the font/formatting. Perhaps there is some other way to fix that, but it sounds like the current "fix" is actually worse than the original problem we were trying to solve.`

**Comment by mcdurdin** [comment]
> However, I had to do the reset on Keyman rather than postevent which gave an error. Why would we specify postevent?

The reason for postevent is lost in time. I do not remember. Certainly it makes sense to do all rather than postevent I think. I went ahead and updated the KB article accordingly.

In terms of #991, I am also not sure. I know that at the time, Tom was struggling to find a stable way to handle the various compatibility issues on mac. We have not had anyone working full time on mac since Tom finished, so there has been little progress. It's something we should sit down and review properly.

**Comment by sgschantz** [comment]
Here is a summary of Amharic test results (different list of apps than above):
**Success**: Firefox, WhatsApp, Pages, Numbers, Notes, TextEdit, Safari, Messages
**Failed 3 and 4**: Atom, Google Docs in Chrome, Google Docs in Firefox
**Failed 2 and 7**: VSCode
**Failed 7**: Slack, Signal

**Comment by sgschantz** [comment]
_Switching to system keyboard or other IM turns off Keyman OSK_
Choosing "Show Keyboard Viewer" from the System Menu causes the Mac OSK to appear but does not close the Keyman OSK. Is this a bug? What if 'Always Show OSK' is enabled?

_Verify behavior and appearance of On-Screen Keyboard and the menu that toggles it on and off._
The OSK menu item "On-screen Keyboad" is not a toggle. It only shows the OSK if it is hidden. I think we should change this design to match the behavior of the Mac OSK "Keyboard Viewer"

**Comment by mcdurdin** [comment]
> _Switching to system keyboard or other IM turns off Keyman OSK_ Choosing "Show Keyboard Viewer" from the System Menu causes the Mac OSK to appear but does not close the Keyman OSK. Is this a bug? What if 'Always Show OSK' is enabled?

I think interactions between the system keyboard viewer and the Keyman OSK have never been defined.

> _Verify behavior and appearance of On-Screen Keyboard and the menu that toggles it on and off._ The OSK menu item "On-screen Keyboad" is not a toggle. It only shows the OSK if it is hidden. I think we should change this design to match the behavior of the Mac OSK "Keyboard Viewer"

Agreed.
