### ISSUE TITLE
feat(web): tweak meaning of `&layerChanged` store to reflect name of new layer

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyman#6364]
This is a proposal to change the meaning of the `&layerChanged` system store so that instead of just being a boolean value, it returns the name of the new layer selected. Given the `&layerChanged` store is only available during the `postKeystroke` processing, this should have no impact on existing keyboards. The `&layerChanged` store is new in Keyman 15.0 and this change would need to be applied in the 15.0 beta cycle (as of writing we are at 15.0.211-beta).

The store could have three possible values, set in the following circumstances:
* If no layer change occurs with a given keystroke, then the store value would be an empty string.
* If the user touches a key which has a `next layer` property that is not `(none)`, then the value of `&layerChanged` would be the name of that next layer -- even if the next layer is _the same layer_. See discussion below.
* If any rule is matched that includes a `layer` statement in the output, the last `layer` statement fired in the rule processing for that keystroke would determine the value in `&layerChanged` -- even if the next layer is _the same layer_.

About the value of `&layerChanged` when the next layer is set to _the same layer_: this gives us the ability to easily say that a given key, e.g. on the shift layer, should not trigger a layer change, i.e. the opposite of the default action for that layer. It is still possible to do this, by matching on the output of that key and skipping the layer reset in the `postKeystroke` processing, but that is more indirect. This is also new behaviour -- the original implementation would have returned `0` in this case.

**Comment by mcdurdin** [comment]
* @ermshiperete suggests renaming the store to `&newLayer`.
* Ref https://community.software.sil.org/t/keyman-15-beta-feedback/5755/17

# TODO

- [ ] Rename store in all Developer and web and app references.
- [ ] Change value provided in store in web, and update logic on change per the spec above.
- [ ] Update sample and test keyboards
- [ ] Update documentation
