### ISSUE TITLE
test(iOS): Regression test for #6525

### ISSUE THREAD

**Issue by MakaraSok** [keymanapp/keyman#6692]
# Keyman for iPhone and iPad Acceptance Test Procedures #

1. These test procedures are to be run before moving from alpha to beta, or beta to stable, or before PRs are merged into stable branches.
2. Copy these tests into a new issue (for tier transitions) or a comment on the PR.
3. When annotating results, use `>` at the start of a new line under the checkbox to note the result. (For an example, see #3973).

---

# User Testing
## Gather Assets for Testing ##
- [ ] Record device's iOS version
- [ ] Ensure the device/simulator is properly configured for testing and is registered with TestFlight. 
- [ ] The Keyman for iOS build can be found at https://github.com/keymanapp/keyman/pull/6525

At this time, Keyman for iOS does not support external keyboard input.

## Setup Steps ##
1.  Uninstall previous version of Keyman on the device (on a simulator, "Erase All Content and Settings..." under Device menu)
2. Install test build IPA (on a simulator, "[iOS Simulator Image](https://build.palaso.org/repository/download/Keyman_iOS_TestPullRequests/321011:id/upload/16.0.11/keyman-ios-simulator-16.0.11.app.zip)")
3. Disable internet connectivity of the device
4. Start Keyman and select **Add a keyboard for your language**
5. Verify error message "Could not reach Keyman server!" or "The Internet connection appears to be offline." is displayed
6. Click OK to dismiss.  Close Keyman app
7. On device, enable internet connectivity
8. Start Keyman
9. On initial **Get Started** menu, select "Enable Keyman as system-wide keyboard" and do any necessary system steps to enable Keyman

---

## SUITE_INSPECT: Visual Inspection of alpha-test-6525 branch
- TEST_BUILD_STATUS_ALPHA_6525: Verify latest CI build of [Keyman for iOS on the branch](https://build.palaso.org/buildConfiguration/Keyman_iOS_TestPullRequests/321011?hideProblemsFromDependencies=false&hideTestsFromDependencies=false&expandBuildChangesSection=true) is successful
- TEST_VERIFY_HISTORY: Verify [`HISTORY.md`](https://github.com/keymanapp/keyman/blob/chore/web/no-more-lerna/HISTORY.md) contains all the current changes
- disable_TEST_VERIFY_UNIT_TESTS: Verify that all unit tests for iOS are currently passing.
    - May be integrated with the first step above once our usual CI processes include the iOS unit tests.

---

## SUITE_MENU_FUNCTIONALITY: Menu Functionality Tests, in-app##
- GROUP_IPHONE_PORTRAIT: portrait mode in iPhone
- GROUP_IPHONE_LANDSCAPE: landscape mode in iPhone
- GROUP_IPAD_PORTRAIT: portrait mode in iPad
- GROUP_IPAD_LANDSCAPE: landscape mode in iPad

### Test Cases
- **TEST_GET_STARTED**: Get Started
  - Verify touching **Add a keyboard for your language** pulls up the **keyboard search**
      - This should also be accessible as **Settings** > **Installed Languages** > **`+`**.
  - Verify touching **Enable Keyman as system-wide keyboard** pulls up Keyman's menu within iOS settings.  (11.0+ devices)
      - If older versions of iOS are supported, ensure that the help page for doing it manually is properly linked.
  - Verify touching **More info** brings up an accurate version and the main table-of-contents help page.
      - This should also be accessible as **Info** from the main menu dropdown (on phones) or as the circled-i button (on tablets).
  - Set **Don't show again** to checked, close and re-open Keyman, and verify **Get Started** menu does not appear

- **TEST_ADD_NEW_KEYBOARD**: Add New Keyboard
This menu is accessed via **Get Started** menu or **Settings** menu
  - On the device, enable internet connectivity
  - Verify a new keyboard can be downloaded and selected, say "US Basic"
  - Return to the text input screen and confirm that it operates correctly.
  - Without changing selected language, confirm that it can be cleanly deleted via the Settings menu.
  - Confirm that another keyboard is correctly selected afterward.

- **TEST_ADD_NEW_KEYBOARD_FROM_FILE**:
  - On the device, go to keyman.com on Safari
  - Search for "US Basic"
  - scroll down to keyboard details and tap to download the keyboard package (i.e. `.kmp` file)
  - open Files app and navigate to Download folder to find "basic_kbdus.kmp" and tap on it to start the installation processes
  - Keyman app should be pulled up
  - follow the screen to finish the keyboard installation
  - verity that the keyboard is correctly installed and working as expected

- **TEST_SWITCH_KEYBOARD**
  - press on the globe key
  - the keyboard menu should be shown
  - press on a keyboard to switch to, say "EuroLatin (SIL)"
  - confirm that "EuroLatin (SIL)" is now selected and ready to be used
  - swich back to "US Basic" and confirm it does as expected

- **TEST_SHARE**: Share
  - Type and verify text can be copied and shared to external app

- **TEST_KEYMAN_BROWSER**: Keyman Browser ###
  - On default page, click on text field and set system keyboard to Keyman
  - Verify can type with Keyman as system keyboard
  - Verify that predictive suggestions are properly applied when selected (using `sil_euro_latin` + English)
  - Close and reopen Keyman app

- **TEST_TEXT_SIZE**: Text Size
  - Verify text can be rescaled from Text Size 9 to 72

- **TEST_CLEAR_TEXT**: Clear Text
  - Verify text can be cleared

- **TEST_INFO**: Info
  - Verify that the Keyman iOS version is displayed; record the version
  - Verify that the Info menu options matches that of the **More Info...** option from the **Get Started** menu option.
  - Verify that the Keyman iOS version matches the version string seen at (Home Screen) > [iOS] Settings > Keyman.

- **TEST_SETTINGS**: Settings
  - Installed Languages ... Add Language
  - Select an installed language ... Add (another) Keyboard
    - Should automatically perform a filtered search based upon that language's BCP-47 code, i.e. for "English" it should be seen as shown in the screenshot below.
    <img width="150" src="https://user-images.githubusercontent.com/28331388/163088289-b467eabb-01a6-468e-81f9-2cfad38584bd.png">

  - Select an installed language ... Dictionary
    - Turn on/off 'Enable Predictions' and validate each
    - Turn on/off 'Enable Corrections' and validate each
  - Validate that when both predictions and corrections are off, banner is not visible
  - Add/Remove dictionaries - validate
  - If multiple dictionaries are available, test swapping between them

- **TEST_EUROLATIN**: `English (Eurolatin)` in-app
  - Verify that the OSK appears and fills the width the bottom of the screen
  - Verify long-press `q` key works
  - Verify long-press `k` key works
      - Verify that any predictive suggestions generated feel 'reasonable' (based upon 'k', the selected subkey, or one of its neighbors)
  - Verify uppercase layer can be selected via `SHIFT`
  - Verify number layer can be selected via `123`
  - Verify long-press `1` key works
  - Verify long-press `0` key works
  - Verify backspace, space, and enter keys work

Note that EuroLatin2, a highly customized keyboard explicitly designed for mobile, is not found; hence EuroLatin (SIL) is used for testing this instead.

- **TEST_US_BASIC**: English: `US Basic` in-app
  - Verify that the **US Basic** keyboard can be downloaded through Settings > Installed Languages > English > `+`
    - This should automatically bring up search results for **English** keyboards.
    - When the package-installer launches, English should be the one pre-selected language.
  - Install the package for both English and Tagalog by selecting both of them in the installation processes.
  - Set **English: US Basic** as the active in-app keyboard.
  - Verify that predictive text suggestions appear.
  - Set **Tagalog: US Basic** as the active in-app keyboard.
  - Verify that predictive text suggestions do _not_ appear.
  - Verify that long-press `123` key works, presenting options for a currency layer and a symbol layer.
  - Select the currency layer, then press the `£` key.
  - Verify that the keyboard outputs correctly and returns to the default layer.
  - Go to the symbol layer and press the `©` key.
  - Verify that the keyboard outputs correctly and remains on the symbol layer.
  - Revert to the default layer and ensure basic key inputs work.
  - Long-press `e` on the default layer and select a subkey.
  - Verify that the selected key produces the correct output.
  - From the `Settings > Languages > English > US Basic` menu, follow the "Help link" and ensure it displays appropriate help.
    - (Should work both online and offline)
  - From the `Settings > Languages > English > US Basic` menu, scan the QR code with a phone and test that it links to the current version of that keyboard's public download page on keyman.com.
  - Returning to the app, uninstall the **US Basic** keyboard via Settings for Tagalog.
  - Set **English: US Basic** as the active in-app keyboard.
  - Verify that the keyboard appears correctly and ensure basic key inputs work.
    - This is to ensure that uninstalling for one language doesn't adversely affect installations of the same resource for another language.
  - Uninstall the **US Basic** keyboard via Settings for English.

---

## SUITE_SYSTEM_KEYBOARD:
- GROUP_IPHONE_PORTRAIT: portrait mode in iPhone
- GROUP_IPHONE_LANDSCAPE: landscape mode in iPhone
- GROUP_IPAD_PORTRAIT: portrait mode in iPad
- GROUP_IPAD_LANDSCAPE: landscape mode in iPad

Test the following after setting Keyman as a system keyboard.

Test Cases
- **TEST_BASIC_USAGE**: ensure that the keyboards functions as expected on all layers. Please test on multiple keyboards, i.e. EuroLatin (SIL), Cameroon QWERTY keyboard and Khmer Angkor.
- **TEST_LONG_PRESS**: ensure that longpress on all applicable layers are working as intended
- **TEST_GLOBE_KEY**: ensure that a short press on the globe key switch to the next keyboard and a longpress on it open the keyboard menu where you can select a keyboard of your choice

## SUITE_SWITCH_LOCALE
- GROUP_IPHONE_PORTRAIT: portrait mode in iPhone
- GROUP_IPHONE_LANDSCAPE: landscape mode in iPhone
- GROUP_IPAD_PORTRAIT: portrait mode in iPad
- GROUP_IPAD_LANDSCAPE: landscape mode in iPad

### Test Cases
- **TEST_KM_LOCALE** 
  - from System Preferences, switch the UI language to Khmer by adding it in `Language & Region` using `+`
  - drag Khmer to the top of the list to set it as a primary UI language
  - restart the machine
  - check the dropdown menu to see it in Khmer
  - verify the UI language of Keyman on the dropdown menu and Keyman `Configuration...` switch to Khmer
  - file a bug if anything on all windows of `Keyman Configuration` stays in EN while it should be in the selected locale
- **TEST_AM_LOCALE**
  - from System Preferences, switch the UI language to Amharic by adding it in `Language & Region` using `+`
  - drag Amharic to the top of the list to set it as a primary UI language
  - restart the machine
  - check the dropdown menu to see it in Amharic
  - verify the UI language of Keyman on the dropdown menu and Keyman `Configuration...` switch to Amharic
  - file a bug if anything on all windows of `Keyman Configuration` stays in EN while it should be in the selected locale

---

## [TODO] SUITE_PREDICTIVE_TEXT: Predictive Text

**Comment by bharanidharanj** [comment]
## SUITE_INSPECT: Visual Inspection of alpha-test-6525 branch

* **TEST_BUILD_STATUS_ALPHA_6525 (PASSED):** The CI build of Keyman Alpha 16.0.11 is successful. 

* **TEST_VERIFY_HISTORY (PASSED):** Verified the History page and it seems to be updated. 

<img width="300" src="https://user-images.githubusercontent.com/19683143/171817860-235570cd-28a8-48e2-a8ae-06ce214c67b4.PNG">

**Comment by bharanidharanj** [comment]
## SUITE_MENU_FUNCTIONALITY: Menu Functionality Tests, in-app##

### GROUP_IPHONE_PORTRAIT: portrait mode in iPhone

* **TEST_GET_STARTED (PASSED):** Tested Keyman 16.0.11-alpha build in iPhone 13 Pro Max Simulator as per the instructions and it is working as expected. 
* **TEST_ADD_NEW_KEYBOARD (PASSED):** Tested Keyman 16.0.11-alpha build in iPhone 13 Pro Max Simulator as per the instructions and it is working as expected. 
* **TEST_ADD_NEW_KEYBOARD_FROM_FILE (PASSED):** Tested Keyman 16.0.11-alpha build in iPhone 13 Pro Max Simulator as per the instructions and it is working as expected. 
* **TEST_SWITCH_KEYBOARD (PASSED):** Tested Keyman 16.0.11-alpha build in iPhone 13 Pro Max Simulator as per the instructions and it is working as expected. 
* **TEST_SHARE (PASSED):** Tested Keyman 16.0.11-alpha build in iPhone 13 Pro Max Simulator as per the instructions and it is working as expected. 
* **TEST_KEYMAN_BROWSER (PASSED):** Tested Keyman 16.0.11-alpha build in iPhone 13 Pro Max Simulator as per the instructions and it is working as expected. 
* **TEST_TEXT_SIZE (PASSED):** Tested Keyman 16.0.11-alpha build in iPhone 13 Pro Max Simulator as per the instructions and it is working as expected. 
* **TEST_CLEAR_TEXT (PASSED):** Tested Keyman 16.0.11-alpha build in iPhone 13 Pro Max Simulator as per the instructions and it is working as expected. 
* **TEST_INFO (PASSED):** Tested Keyman 16.0.11-alpha build in iPhone 13 Pro Max Simulator as per the instructions and it is working as expected. 

<img width="300" src="https://user-images.githubusercontent.com/19683143/171856430-ee1dc4c9-34cf-4994-ab31-9fd637f25f2f.png"> 


* **TEST_SETTINGS (PASSED):** Tested Keyman 16.0.11-alpha build in iPhone 13 Pro Max Simulator as per the instructions and it is working as expected. 
* **TEST_EUROLATIN (PASSED):** Tested Keyman 16.0.11-alpha build in iPhone 13 Pro Max Simulator as per the instructions and it is working as expected. 
* **TEST_US_BASIC (PASSED):** Tested Keyman 16.0.11-alpha build in iPhone 13 Pro Max Simulator as per the instructions and it is working as expected.

**Comment by bharanidharanj** [comment]
## SUITE_MENU_FUNCTIONALITY: Menu Functionality Tests, in-app##

### GROUP_IPHONE_LANDSCAPE: landscape mode in iPhone

* **TEST_GET_STARTED (PASSED):** Tested Keyman 16.0.11-alpha build in iPhone 13 Pro Max Simulator as per the instructions and it is working as expected.
* **TEST_ADD_NEW_KEYBOARD (PASSED):** Tested Keyman 16.0.11-alpha build in iPhone 13 Pro Max Simulator as per the instructions and it is working as expected.
* **TEST_ADD_NEW_KEYBOARD_FROM_FILE (PASSED):** Tested Keyman 16.0.11-alpha build in iPhone 13 Pro Max Simulator as per the instructions and it is working as expected.
* **TEST_SWITCH_KEYBOARD (PASSED):** Tested Keyman 16.0.11-alpha build in iPhone 13 Pro Max Simulator as per the instructions and it is working as expected.
* **TEST_SHARE (PASSED):** Tested Keyman 16.0.11-alpha build in iPhone 13 Pro Max Simulator as per the instructions and it is working as expected.
* **TEST_KEYMAN_BROWSER (PASSED):** Tested Keyman 16.0.11-alpha build in iPhone 13 Pro Max Simulator as per the instructions and it is working as expected.
* **TEST_TEXT_SIZE (PASSED):** Tested Keyman 16.0.11-alpha build in iPhone 13 Pro Max Simulator as per the instructions and it is working as expected.
* **TEST_CLEAR_TEXT (PASSED):** Tested Keyman 16.0.11-alpha build in iPhone 13 Pro Max Simulator as per the instructions and it is working as expected.
* **TEST_INFO (PASSED):** Tested Keyman 16.0.11-alpha build in iPhone 13 Pro Max Simulator as per the instructions and it is working as expected.
* **TEST_SETTINGS (PASSED):** Tested Keyman 16.0.11-alpha build in iPhone 13 Pro Max Simulator as per the instructions and it is working as expected.
* **TEST_EUROLATIN (PASSED):** Tested Keyman 16.0.11-alpha build in iPhone 13 Pro Max Simulator as per the instructions and it is working as expected.
* **TEST_US_BASIC (PASSED):** Tested Keyman 16.0.11-alpha build in iPhone 13 Pro Max Simulator as per the instructions and it is working as expected.

**Comment by bharanidharanj** [comment]
## SUITE_MENU_FUNCTIONALITY: Menu Functionality Tests, in-app##

### GROUP_IPAD_PORTRAIT: portrait mode in iPad

* **TEST_GET_STARTED (PASSED):** Tested Keyman 16.0.11-alpha build in iPad (9th generations) iOS 15.5 Simulator as per the instructions and it is working as expected.
* **TEST_ADD_NEW_KEYBOARD (PASSED):** Tested Keyman 16.0.11-alpha build in iPad (9th generations) iOS 15.5 Simulator as per the instructions and it is working as expected.
* **TEST_ADD_NEW_KEYBOARD_FROM_FILE (PASSED):** Tested Keyman 16.0.11-alpha build in iPad (9th generations) iOS 15.5 Simulator as per the instructions and it is working as expected.
* **TEST_SWITCH_KEYBOARD (PASSED):** Tested Keyman 16.0.11-alpha build in iPad (9th generations) iOS 15.5 Simulator as per the instructions and it is working as expected.
* **TEST_SHARE (PASSED):** Tested Keyman 16.0.11-alpha build in iPad (9th generations) iOS 15.5 Simulator as per the instructions and it is working as expected.
* **TEST_KEYMAN_BROWSER (PASSED):** Tested Keyman 16.0.11-alpha build in iPad (9th generations) iOS 15.5 Simulator as per the instructions and it is working as expected.
* **TEST_TEXT_SIZE (PASSED):** Tested Keyman 16.0.11-alpha build in iPad (9th generations) iOS 15.5 Simulator as per the instructions and it is working as expected.
* **TEST_CLEAR_TEXT (PASSED):** Tested Keyman 16.0.11-alpha build in iPad (9th generations) iOS 15.5 Simulator as per the instructions and it is working as expected.
* **TEST_INFO (PASSED):** Tested Keyman 16.0.11-alpha build in iPad (9th generations) iOS 15.5 Simulator as per the instructions and it is working as expected.

<img width="300" src="https://user-images.githubusercontent.com/19683143/171874612-e615b6ad-5898-46c8-a5f4-b0904cc2fa24.png"> 

* **TEST_SETTINGS (PASSED):** Tested Keyman 16.0.11-alpha build in iPad (9th generations) iOS 15.5 Simulator as per the instructions and it is working as expected.
* **TEST_EUROLATIN (PASSED):** Tested Keyman 16.0.11-alpha build in iPad (9th generations) iOS 15.5 Simulator as per the instructions and it is working as expected.
* **TEST_US_BASIC (PASSED):** Tested Keyman 16.0.11-alpha build in iPad (9th generations) iOS 15.5 Simulator as per the instructions and it is working as expected.

### GROUP_IPAD_LANDSCAPE: landscape mode in iPad

* **TEST_GET_STARTED (PASSED):** Tested Keyman 16.0.11-alpha build in iPad (9th generations) iOS 15.5 Simulator as per the instructions and it is working as expected.
* **TEST_ADD_NEW_KEYBOARD (PASSED):** Tested Keyman 16.0.11-alpha build in iPad (9th generations) iOS 15.5 Simulator as per the instructions and it is working as expected.
* **TEST_ADD_NEW_KEYBOARD_FROM_FILE (PASSED):** Tested Keyman 16.0.11-alpha build in iPad (9th generations) iOS 15.5 Simulator as per the instructions and it is working as expected.
* **TEST_SWITCH_KEYBOARD (PASSED):** Tested Keyman 16.0.11-alpha build in iPad (9th generations) iOS 15.5 Simulator as per the instructions and it is working as expected.
* **TEST_SHARE (PASSED):** Tested Keyman 16.0.11-alpha build in iPad (9th generations) iOS 15.5 Simulator as per the instructions and it is working as expected.
* **TEST_KEYMAN_BROWSER (PASSED):** Tested Keyman 16.0.11-alpha build in iPad (9th generations) iOS 15.5 Simulator as per the instructions and it is working as expected.
* **TEST_TEXT_SIZE (PASSED):** Tested Keyman 16.0.11-alpha build in iPad (9th generations) iOS 15.5 Simulator as per the instructions and it is working as expected.
* **TEST_CLEAR_TEXT (PASSED):** Tested Keyman 16.0.11-alpha build in iPad (9th generations) iOS 15.5 Simulator as per the instructions and it is working as expected.
* **TEST_INFO (PASSED):** Tested Keyman 16.0.11-alpha build in iPad (9th generations) iOS 15.5 Simulator as per the instructions and it is working as expected.
* **TEST_SETTINGS (PASSED):** Tested Keyman 16.0.11-alpha build in iPad (9th generations) iOS 15.5 Simulator as per the instructions and it is working as expected.
* **TEST_EUROLATIN (PASSED):** Tested Keyman 16.0.11-alpha build in iPad (9th generations) iOS 15.5 Simulator as per the instructions and it is working as expected.
* **TEST_US_BASIC (PASSED):** Tested Keyman 16.0.11-alpha build in iPad (9th generations) iOS 15.5 Simulator as per the instructions and it is working as expected.

**Comment by bharanidharanj** [comment]
## SUITE_SYSTEM_KEYBOARD: 

### GROUP_IPHONE_PORTRAIT: portrait mode in iPhone

* **TEST_BASIC_USAGE (PASSED):** Tested Keyman 16.0.11-alpha build in iPhone 13 Pro Max Simulator as per the instructions and it is working as expected.
* **TEST_LONG_PRESS (PASSED):** Tested Keyman 16.0.11-alpha build in iPhone 13 Pro Max Simulator as per the instructions and it is working as expected.
* **TEST_GLOBE_KEY (PASSED):** Tested Keyman 16.0.11-alpha build in iPhone 13 Pro Max Simulator as per the instructions and it is working as expected.

**Comment by bharanidharanj** [comment]
## SUITE_SYSTEM_KEYBOARD: 

### GROUP_IPHONE_LANDSCAPE: landscape mode in iPhone

* **TEST_BASIC_USAGE (PASSED):** Tested this with Keyman 16.0.11-alpha build in iPhone 13 Pro Max Simulator (in Khmer, Cameroon Qwerty and EuroLatin (SIL)) and it is working as expected. 
* **TEST_LONG_PRESS (PASSED):** Tested this with Keyman 16.0.11-alpha build in iPhone 13 Pro Max Simulator (in Khmer, Cameroon Qwerty and EuroLatin (SIL)) and it is working as expected.
* **TEST_GLOBE_KEY (PASSED):** Tested this with Keyman 16.0.11-alpha build in iPhone 13 Pro Max Simulator (in Khmer, Cameroon Qwerty and EuroLatin (SIL)) and it is working as expected.

**Comment by bharanidharanj** [comment]
## SUITE_SWITCH_LOCALE: 

### GROUP_IPHONE_PORTRAIT: portrait mode in iPhone

* **TEST_AM_LOCALE (PASSED):** Tested this with Keyman 16.0.11-alpha build in iPhone 13 Pro Simulator and the UI of the Keyman menu has been changed into Amharic language. 

### GROUP_IPHONE_LANDSCAPE: landscape mode in iPhone

* **TEST_KM_LOCALE (PASSED):** Tested this with Keyman 16.0.11-alpha build in iPhone 13 Pro Simulator and the UI of the Keyman menu has been changed into Khmer language. 
* **TEST_AM_LOCALE (PASSED):** Tested this with Keyman 16.0.11-alpha build in iPhone 13 Pro Simulator and the UI of the Keyman menu has been changed into Amharic language.

**Comment by bharanidharanj** [comment]
## SUITE_SYSTEM_KEYBOARD: 

### GROUP_IPAD_PORTRAIT: portrait mode in iPad

* **TEST_BASIC_USAGE (PASSED):** Tested this with Keyman 16.0.11-alpha build in iPad 9th generation (iOS 15.5) Simulator (in Khmer, Cameroon Qwerty and EuroLatin (SIL)) and it is working as expected.
* **TEST_LONG_PRESS (PASSED):** Tested this with Keyman 16.0.11-alpha build in iPad 9th generation (iOS 15.5) Simulator (in Khmer, Cameroon Qwerty and EuroLatin (SIL)) and it is working as expected.
* **TEST_GLOBE_KEY (PASSED):** Tested this with Keyman 16.0.11-alpha build in iPad 9th generation (iOS 15.5) Simulator (in Khmer, Cameroon Qwerty and EuroLatin (SIL)) and it is working as expected.

### GROUP_IPAD_LANDSCAPE: landscape mode in iPad

* **TEST_BASIC_USAGE (PASSED):** Tested this with Keyman 16.0.11-alpha build in iPad 9th generation (iOS 15.5) Simulator (in Khmer, Cameroon Qwerty and EuroLatin (SIL)) and it is working as expected.
* **TEST_LONG_PRESS (PASSED):** Tested this with Keyman 16.0.11-alpha build in iPad 9th generation (iOS 15.5) Simulator (in Khmer, Cameroon Qwerty and EuroLatin (SIL)) and it is working as expected.
* **TEST_GLOBE_KEY (PASSED):** Tested this with Keyman 16.0.11-alpha build in iPad 9th generation (iOS 15.5) Simulator (in Khmer, Cameroon Qwerty and EuroLatin (SIL)) and it is working as expected.

**Comment by mcdurdin** [comment]
Thank you @bharanidharanj!
