### ISSUE TITLE
chore(developer): additional tests for kmc-package 🗜

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyman#7353]
From #7341.

TODO:

- [ ] Given the number of faults in earlier versions of the package compiler, we will need to review our generation of lexical model packages at some point.
- [ ] Regression test lexical model packages built against Android & iOS
- [x] #9713

And additional work to help this:

- [x] Verify schemas for .kps, kmp.json

**Comment by mcdurdin** [comment]
Remaining TODO items tracked in #9235 (consolidation of TODO lists)
