### ISSUE TITLE
feat(developer): compiler updates for ldml transforms 🙀

### ISSUE THREAD

**Issue by srl295** [keymanapp/keyman#7377]
Updates to compiler for anything pertaining to transforms / UnicodeSets

Blocks #7375

#7042

**Comment by srl295** [comment]
https://github.com/keymanapp/keyman/pull/8695 review parkinglot:
- [ ] https://github.com/keymanapp/keyman/pull/8695/files#r1223611629 merge common IDs

**Comment by srl295** [comment]
I think the only remaining _known_ issue here is:

- [ ] need to support reorder -> externalized `uset` section

**Comment by srl295** [comment]
final todos:
- [ ] support `<reorder from="\u{0127 0128}">` as equivalent to `<reorder from="\u{0127}\u{0128}">
- [ ] refactor KmnCompiler instances for uset

**Comment by srl295** [comment]
Markers are in separate tickets, so declaring this one done for now. re basic implementation.
