### ISSUE TITLE
feat(developer): add feature flag to control use of kmcompx 🚑

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyman#7947]
### Is your feature request related to a problem? Please describe.

The feature-kmcompx epic needs a feature flag to allow end users to switch back to the old compiler in case of issues with the new version of the compiler. The feature flag needs to be accessible as a registry setting (for use by TIKE and kmcomp), and also as a command line option to kmcomp, which overrides the registry setting.

### Describe the solution you'd like

Suggestions:

`HKCU\Software\Keyman\Keyman Developer: "use kmcompx compiler" [REG_DWORD]`:
  - not present = true
  - 0 = false
  - 1 = true

`kmcomp` command line:
  - no parameter -- use registry value
  - `kmcomp -use-kmcompx` -- overrides registry value = true
  - `kmcomp -no-use-kmcompx` -- overrides registry value = false

The name `kmcompx` is subject to change. Any ideas for a more user-friendly and intuitive name?

### Keyman apps

- [ ] Keyman for Android
- [ ] Keyman for iPhone and iPad
- [ ] Keyman for Linux
- [ ] Keyman for macOS
- [ ] Keyman for Windows
- [X] Keyman Developer
- [ ] KeymanWeb
- [ ] Other - give details at bottom of form

### Keyman version

17.0-alpha
