### ISSUE TITLE
feat(developer): KeymanWeb Typescript Compiler 🗜

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyman#8955]
## TODO

Future build infrastructure:
* `# TODO: remove c8 exclusion of coverage of kmw-compiler folder`

**various files:**
* [x] #8956
* [x] Sort out discrepancy between `color` and `style` in `VisualKeyboardFont` --> #9054
* [x] #8957
* [x] #8958
* [x] Lifecycle for global variables, put them all in one place at least, to start with (#9046)
* [x] Invert kmc-kmn and kmc-kmw dependency -- make kmc-kmn dependent on kmc-kmw rather than vice-versa --> #9038

Future common/web/types work:
* Review consistency of various common/web/types readers and writers (group task would be good?)

**javascript-strings.ts:**
* [x] Move constant declarations such as VKeyNames into separate units (in a _consts_ folder?)  (#9046)
* [x] kmx compiler needs to support build-to-memory-buffer
* [x] `// TODO: lifecycle` (#9046)
* [x] Get readonly groups and store metadata from kmx compiler when building for .js --> #9076
* [x] `// TODO: export group + store metadata in debug store, use that` --> #9076
* [x] Remove various commented code sections (mostly Delphi variable declarations) --> #9086
* [x] `// TODO: problems with supp chars` --> #9086
* [x] `// TODO: move elsewhere`

Following TODO items are from the Delphi code:
* `// TODO:  Refactor the section below into JavaScript_String, as it's`
* `// TODO: this doesn't resolve the issue of, e.g. SHIFT+K_SPACE`
* `// TODO: context character level switches instead of full context comparisons`

**validate-layout-file.ts:**
* [x] variable lifecycle (#9046)
* [x] `// TODO lifecycle` (#9046)
* [x] error reporting --> #9087
* [x] `// TODO: callbacks.reportMessage() ReportError(0, CWARN_TouchLayoutMissingLayer, 'Key "'+FId+'" on platform "'+FPlatform.Name+'", layer "'+FLayer.Id+'", platform "'+FPlatform.Name+'", references a missing layer "'+FNextLayer+'".');      ` --> #9087
* [x] `// TODO: ReportError(0, CWARN_TouchLayoutUnidentifiedKey, 'A key on layer "'+FLayer.Id+'" has no identifier.');` --> #9087
* [x] `// TODO: ReportError(0, CERR_TouchLayoutInvalidIdentifier, 'Key "'+FId+'" on "'+FPlatform.Name+'", layer "'+FLayer.Id+'" has an invalid identifier.');` --> #9087
* [x] `// TODO: ReportError(0, CERR_TouchLayoutInvalidIdentifier, 'Key "'+FId+'" on "'+FPlatform.Name+'", layer "'+FLayer.Id+'" has a multi-part identifier which requires version 15.0 or newer.');` --> #9087
* [x] `// TODO: ReportError(0, CWARN_TouchLayoutCustomKeyNotDefined, 'Key "'+FId+'" on layer "'+FLayer.Id+'", platform "'+FPlatform.Name+'", is a custom key but has no corresponding rule in the source.');` --> #9087
* [x] `// TODO: ReportError(0, CWARN_TouchLayoutSpecialLabelOnNormalKey,` --> #9087
* [x] `// TODO: ReportError(fkp.Line, CERR_InvalidKeyCode, 'Invalid key identifier "'+FDictionary[i]+'"');` --> #9087
* [x] `// TODO: ReportError(0, CERR_InvalidTouchLayoutFile, sMsg);` --> #9087
* [x] `// TODO: ReportError(0, CWARN_TouchLayoutFontShouldBeSameForAllPlatforms, 'The touch layout font should be the same for all platforms.');` --> #9087
* [x] `// TODO: ReportError(0, CWARN_TouchLayoutMissingRequiredKeys, 'Layer "'+FLayer.Id+'" on platform "'+FPlatform.Name+'" is missing the required key(s) '+RequiredKeysToString(CRequiredKeys-FRequiredKeys)+'.');` --> #9087

Future lowpri TODO items:
* `// TODO: O(eeek) performance here`
* `// TODO: why support multiple font values if it has to be the same across all platforms?!`

**visual-keyboard-compiler.ts:**
* [x] support bold, italic --> #9054
* [x] `// TODO 'bold ' if visualKeyboard.header.unicodeFont.style` --> #9054
* [x] `// TODO 'italic ' if visualKeyboard.header.unicodeFont.style` --> #9054
* [x] refactor displayUnderlying flag (it's also misspelled) --> #9056
* [x] `// TODO: this can go in caller, later` --> #9056

**visual-keyboard.ts:**
* [x] `// TODO: figure out style vs color issues` --> #9054

**kmw-compiler.ts:**
* [x] `Keyboard_name` needs to be cleaned (done earlier)
* [x] sHelpFile is never populated --> #9058
* [x] sEmbedJS is never populated --> #9058
* [x] sEmbedCSS is never populated --> #9058
* [x] `const sName = 'Keyboard_'+name; //TODO: verify --> GetKeymanWebCompiledNameFromFileName(FInFile);` (done earlier)
* [x] `//TODO: load sHelpFile from file` --> #9058
* [x] `//TODO: load sEmbedJS from file` --> #9058
* [x] `//TODO: load sEmbedCSS from file` --> #9058
* [x] `// TODO: error` --> #9056
* [x] `// TODO: reusing the same variable here is ugly` --> #9058
* [x] `// TODO: stop reusing sVisualKeyboard for both filename and content` --> #9056
* [x] Fixup isOptionStore (see also 'get readonly groups' task) --> #9075
* [x] `// TODO: how do we determine this, see CheckStoreUsage()` --> #9075
* [x] rename it from write-compiled-keyboard.ts to kmw-compiler.ts --> #9088
* [x] IMX support (FCallFunctions) --> #9088
* [x] Complete HasSupplementaryPlaneChars --> #9088
* [x] `// TODO: log errors`
* [x] `/* TODO`
* [x] `return false; // TODO`
* [x] Error reporting
* [x] VKDictionary
* [x] `reader.validate(source, callbacks.loadSchema("kvks")); // TODO: handle exceptions`

Future lowpri TODO items:
* `//TODO: We need to think about mnemonic layouts which are incompletely supported at present`
* ladderlength const could be an option? 
* `export let FFix183_LadderLength: number = 100; // TODO: option`
* `// TODO: use a JSON encode`
* `// TODO(lowpri): rename error constant to Warn_EmbedFileMissing`
* `// TODO: add FTabStop to line above, once we have 100% identical match ...`

**messages.ts:**
* [x] #8986
* [x] `// TODO: these Codes Are All Wrong But We'll  Fix It Soon` --> see above

Future lowpri TODO items:
* Extend KmwCompilerMessages to report filename and line number more reliably

**test/test-compiler-manual.ts:**
* [x] `// TODO: runToMemory, add option to kmxCompiler to store debug-data for conversion to .js (e.g. store metadata, group readonly metadata, etc)`

**test/test-compiler.ts:**
* [x] `// TODO: runToMemory, add option to kmxCompiler to store debug-data for conversion to .js (e.g. store metadata, group readonly metadata, visual keyboard source filename, etc)`

**Comment by mcdurdin** [comment]
Wrong issue number in 57af86e...

**Comment by mcdurdin** [comment]
These issues are all completed in PRs (or are long-term future items which don't currently require tracking). Going ahead and closing this.

Continuing work will be tracked in #9090.
