### ISSUE TITLE
chore(developer): kmc-analyze todo list 🗜

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyman#8969]
Extracted from #8723.

# TODO

**analyze.ts**
- [x] figure out silent vs quiet mode and tidy up NodeCompilerCallbacks (fixed in #8723)
- [x] add info reporting messages (fixed in #8723)
- [x] handle unsupported action type (fixed in #8723)
- [x] consider process.stdout.write instead of console.log for emitting the report (fixed in #8723)
- [x] #8981

**osk-character-use/index.ts**
- [x] // TODO: this.callbacks.reportMessage(...)  console.log(`Scanning project ${filename}`); (fixed in #8723)
- [x] use KmnCompiler.runCompiler so we don't need temp file (fixed in #8723)
- [x] #8985
- [x] #8990
- [x] #8992
- [x] check vk, invalidKeys in scanVisualKeyboard (see above item)
