### ISSUE TITLE
feat(core): ldml marker implementation 🙀

### ISSUE THREAD

**Issue by srl295** [keymanapp/keyman#9119]
depends on #9118 

spec at https://github.com/keymanapp/keyman/blob/master/core/src/ldml/C9134_ldml_markers.md

-----
### TODO area
- [x] markers in lists, such as:
- [x] markers in keys.longPress
- [x] markers in keys.multiTap
- [x] markers in flicks.to
