### ISSUE TITLE
chore(developer): kmc to-do list 🗜

### ISSUE THREAD

**Issue by jahorton** [keymanapp/keyman#9235]
## Follow-up for keymanapp/keyman#8954 (epic/kmc-kmw)

- [x] publish alpha kmc (to npm) + get it working
- [x] fixup keyboards in keyboards repo impacted by kmc (keymanapp/keyboards#2311)
- [x] replace kmcomp with kmc in Keyman Developer (#9539)
- [x] documentation -- see keymanapp/keyman#9351
- [x] create keyboards repo PR to generate static .keyboard_info files for legacy folder -- see keymanapp/keyman#9351
- [x] ensure legacy keyboards 'compile' with kmc -- see keymanapp/keyman#9351
- [x] keymanapp/keyman#8661
- [x] keymanapp/keyman#9158
- [x] keymanapp/keyman#9351
- [x] add PR to keyboards repo for building with kmc (keymanapp/keyboards#2389)
- [x] add PR to models repo for building with kmc (keymanapp/lexical-models#224)

## Follow-up for keymanapp/keyman#9485 (epic/package-metadata)

From keymanapp/keyman#9452 I have the following related PRs:
- [x] keymanapp/api.keyman.com#204
- [x] keymanapp/keyman.com#382
- [x] keymanapp/keyboards#2336
- [x] keymanapp/keyboards#2337
- [x] keymanapp/help.keyman.com#798

From keymanapp/keyman#9459, needs corresponding PRs against api.keyman.com, help.keyman.com, and keyboards repositories:
- [x] keymanapp/api.keyman.com (schema updates)
- [x] keymanapp/keyboards (revised keyboards, blocked until kmc is applied on the repo), see keymanapp/keyman#9351 for links to all the PRs (range 2393-2415).
- [x] keymanapp/help.keyman.com, documentation updates (https://github.com/keymanapp/help.keyman.com/pull/843)
- [x] keymanapp/help.keyman.com, documentation on new kmc build windows-package-installer (https://github.com/keymanapp/help.keyman.com/pull/815)

From keymanapp/keyman#9463, needs corresponding PRs against api.keyman.com, help.keyman.com, and keyboards repositories:

- [x] keymanapp/api.keyman.com (schema updates)
- [x] keymanapp/keyboards (revised keyboards, blocked until kmc is applied on the repo)
- [x] keymanapp/help.keyman.com (documentation updates) (https://github.com/keymanapp/help.keyman.com/pull/843)
- [x] keymanapp/keyboards (s.keyman.com font copy phase, keymanapp/keyboards#2323)

## Follow-up for keymanapp/keyman#9351

On 19 Oct, I moved the remaining items here and grouped them by component, because the list was getting too large to manage.

### keymanapp/keyman
- [x] keymanapp/keyman#9710

### keymanapp/help.keyman.com
- [x] context/edit-language-example (https://github.com/keymanapp/help.keyman.com/pull/843)
- [x] context/edit-related-package page (https://github.com/keymanapp/help.keyman.com/pull/843)
- [x] context/edit-package-web-fonts (https://github.com/keymanapp/help.keyman.com/pull/843)
- [x] context/kmc (https://github.com/keymanapp/help.keyman.com/pull/815)

### From keymanapp/keyman#7353
- [x] Regression test lexical model packages built against Android & iOS
- [x] Verify kmp.json as generated by kmc against the schema (#9844)

### keymanapp/api.keyman.com
- [x] keymanapp/api.keyman.com#212

### keymanapp/keymanweb.com
- [x] keymanapp/keymanweb.com#89

From keymanapp/keyman#9474:
- [x] keymanapp/keyman#9858

### keymanapp/keyboards
- [x] keymanapp/keyboards#2433
