### ISSUE TITLE
bug(developer): kmc deployment issues 🗜

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyman#9249]
We want to deploy to the Keyman Developer installation as an ESM module now. This leads to a number of issues:

- [x] we need a package.json with a `"type": "module"` (or else rename files to .mjs?)
- [x] kmc.cmd refers to kmc/kmc.cjs instead of kmc/kmc.js
- [x] kmc.cmd shouldn't use `--enable-sourcemaps` now because we use sentry instead
- [x] we are missing all required internal and external modules in our bundle
