### ISSUE TITLE
chore: convert remaining TypeScript modules to ESM

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyman#9262]
According to a quick search, only the following modules are not ESM (slightly edited to remove built files):

```
$ find . -name package.json | grep -v node_modules | xargs grep -rL '"type": "module"'
./common/models/types/package.json
./common/test/predictive-text/package.json
./common/tools/hextobin/package.json
./common/web/lm-message-types/package.json
./developer/src/server/package.json
./developer/src/tike/xml/app/package.json
./developer/src/tike/xml/layoutbuilder/jquery-ui/package.json
./package.json
./resources/build/version/package.json
./resources/gosh/package.json
./web/src/test/manual/web/regression-tests/package.json
```

Grouping these by function and listing only the TypeScript modules gives us a much shorter list. In fact, probably the only significant item is developer/src/server. Turning this into a TODO list for conversion to ES Modules!

# TODO: Convert to ESM

## types (.d.ts only)

- [ ] common/models/types
- [ ] common/web/lm-message-types

## deployed modules

- [x] #9672
- [x] #9679

## internal modules (e.g. test tools, build tools)

- [x] #9675
- [x] #9677

## Cleanup

- [ ] top-level metadata files

_Originally posted by @mcdurdin in https://github.com/keymanapp/keyman/issues/8832#issuecomment-1633688752_
