### ISSUE TITLE
chore(developer): kmc metadata compiler TODO 🗜

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyman#9282]
Metadata compiler work:
- [ ] Add model_info and keyboard_info build activities to kmc
- [ ] Add unit tests for model_info
- [ ] Add compiler for keyboard_info
- [ ] Remove filesystem access from model_info compiler
- [ ] Add compiler messages for model_info compiler
- [ ] Support sourcePath field in model_info compiler
- [ ] Support blank or missing .model_info/.keyboard_info with inferred license from LICENSE.md and all other data from package/keyboard sources and binaries

Project refactoring which is not really metadata work but helps:
- [ ] Remove deprecated project fileType references
- [ ] Refactor projectReader in kmc to use projectLoader
- [ ] Separate error code for attempting to load a non-kpj
- [ ]
