### ISSUE TITLE
feat(developer): Support blank or missing .model_info/.keyboard_info 🎺

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyman#9351]
With license from kps:Options/LicenseFile == LICENSE.md, and all other data from package/keyboard sources and binaries

## Generated fields that don't need change.

The following fields are reliably automatically generated, and we should avoid modifying the code for these:
* `id`: from folder name
* `name`: from .kmp (or from .js?)
* `authorName`: from .kmp
* `authorEmail`: from .kmp
* `lastModifiedDate`: when .keyboard_info is generated
* `packageFilename`: from .kmp
* `packageFileSize`: from .kmp
* `jsFilename`: from .js
* `jsFileSize`: from .js
* `isRTL`: from .js or .kmp
* `encodings`: 'unicode'
* `packageIncludes`: from .kmp
* `version`: from .kmp, .js
* `minKeymanVersion`: from .kmp, .js
* `helpLink`: from folder data (id/source/help/id.php existence)
* `platformSupport`: from .kmp, .js
* `sourcePath`: generated from the path in keyboards repo
* `deprecated`: always generated by deprecation references in `links`

Have verified that all release/ and experimental/ keyboards have a .kmp file. This means we can deprecate or even remove the .js parsing, I think, as long as all fields are represented in the .kmp.

## General tasks

- [x] Cleanup the kmc-keyboard-info interface to reduce number of required parameters ➡ keymanapp/keyman#9479
- [x] Verify that all fields are read correctly from .kmp data
- [x] Should we translate `\r\n` to `\n` in kmp.json Description field? ➡ keymanapp/keyman#9476
- [x] `lastModifiedDate` should be date of last commit in folder, which is possible to achieve during release build: `TZ=UTC0 git log -1 --no-merges --date=format:%Y-%m-%dT%H:%M:%SZ --format=%ad` ➡ keymanapp/keyman#9480
- [x] Remove metadata source file references from kmc, e.g. BuildKeyboardInfo.ts, and work from .kpj always. ➡ keymanapp/keyman#9535
- [x] https://github.com/keymanapp/keyboards/issues/2342
- [x] #9620
- [x] help: context/package-editor ➡ keymanapp/help.keyman.com#815
- [x] help: standard file layout for keyboards and models ➡ keymanapp/help.keyman.com#815
- [x] api.keyman.com: Publish all modified schemas to api.keyman.com, updating forwarding rules accordingly. ➡ keymanapp/keyman#9800, keymanapp/api.keyman.com#210, keymanapp/api.keyman.com#211
- [x] keyboards: https://github.com/keymanapp/keyboards/issues/2354 ➡ keymanapp/keyboards#2414, keymanapp/keyboards#2415
- [ ] keyboards: identify legacy/ packages which were updated without version change, as they still have old metadata on downloads.keyman.com, e.g. b/bod has different info on downloads.keyman.com vs api.keyman.com. I think this is because the publish func only copies new files, never overwrites existing files. (I stumbled on this one when testing, there may be others, this happened 3 years ago so it's not high priority to fix now.)
- [ ] keyboards: verify that external keyboards get correct .keyboard_info data (should be in external repo)

## Schema cleanup

- [x] Remove keyboard_info.distribution.json ➡ keymanapp/keyman#9452, keymanapp/api.keyman.com#204
- [x] Rename keyboard_info.source.json to keyboard_info.schema.json ➡ keymanapp/keyman#9452, keymanapp/api.keyman.com#204
- [x] Fixup required fields in keyboard_info.schema.json ➡ keymanapp/keyman#9452, keymanapp/api.keyman.com#204
- [x] Fixup all references to keyboard_info.schema.json on keyman repo ➡ keymanapp/keyman#9452
- [x] Fixup all references to keyboard_info.schema.json on api.keyman.com ➡ keymanapp/api.keyman.com#204
- [x] Fixup all references to keyboard_info.schema.json on keyman.com ➡ keymanapp/keyman.com#382
- [x] Add keyboard_info.schema.json to common/web/types ➡ keymanapp/keyman#9471
- [ ] api.keyman.com: Update database model

The following fields are not available from .kmp, or only partially available. Suggested action:

## `license` field

**Action:** Add to .kps as LicenseFile, then source that.

   - [x] help: update generation data ➡ keymanapp/help.keyman.com#798
   - [x] common: Update .kps schema ➡ keymanapp/keyman#9470
   - [x] common: Update kmp.json schema ➡ keymanapp/keyman#9470
   - [x] kmc-package: Update compiler ➡ keymanapp/keyman#9470
   - [x] tike: Update package editor ➡ keymanapp/keyman#9470
   - [x] developer: update package template to include LICENSE.md. ➡ keymanapp/keyman#9470
   - [x] keymanapp/keyboards: Add LICENSE.md to each .kps file and set LicenseFile. ➡ keymanapp/keyboards#2404
   - [x] kmc-keyboard-info: source from LicenseFile, 'mit' or 'other', hint on anything other than mit. ➡ keymanapp/keyman#9474
   - [x] help: Update schema documentation ➡ keymanapp/help.keyman.com#798

## `description` field

**Action:** Add to .kps, `<Info><Description/></Info>` and kmp.json. Must be Markdown, not HTML, and no HTML embed is supported.

   - [x] common: Update .kps schema ➡ keymanapp/keyman#9459
   - [x] common: Update kmp.json schema ➡ keymanapp/keyman#9459
   - [x] kmc-package: Update compiler ➡ keymanapp/keyman#9459
   - [x] tike: Update package editor ➡ keymanapp/keyman#9459
   - [x] help: Update generation data ➡ keymanapp/help.keyman.com#798
   - [x] kmc-keyboard-info: update compiler ➡ keymanapp/keyman#9474
   - [x] kmc-package: transform MD into HTML ➡ keymanapp/keyman#9476
   - [x] keyboards: Add the description to each .kps file. ➡ keymanapp/keyboards#2407

## `languages` field

This was partially generated from .kps. This is the most complex object.

### `font`, `oskFont` fields

**Action:** We will need new a metadata field in the package to support these -- because we cannot necessarily read it all automatically:
* `family`: from .kmp
* `source[]`: read from .kmp, always make it an array
* `size`: remove from .keyboard_info, unused

- [x] common: update .kps schema ➡ keymanapp/keyman#9463
- [x] kmp.json: add `webOskFonts` and `webDisplayFonts` to `keyboard` ➡ keymanapp/keyman#9463
- [x] kmc-package: extract font metadata and add to kmp.json ➡ keymanapp/keyman#9463
- [x] tike: update package editor ➡ keymanapp/keyman#9463
- [x] common: remove `size` from .keyboard_info schema, make `source` always array ➡ keymanapp/keyman#9471
- [x] update kmc-keyboard-info to remove size, make source always array, generate from kps ➡ keymanapp/keyman#9474
- [x] help.keyman.com: remove `size`, make `source` always an array ➡ keymanapp/help.keyman.com#798
- [x] keyboards: move font data into kps ➡ keymanapp/keyboards#2408
- [x] keyboards: keymanapp/keyboards#2346 ➡ keymanapp/keyboards#2413
- [ ] help.keyman.com: context/edit-package-web-fonts
- [ ] keyboards: Deployment of package-referenced web fonts to s.keyman.com
- [ ] api.keyman.com: update kmw rest api to return updated font data?

### `examples[]{.keys,.text,.note}` field
**Action:** 
* convert into metadata array in .kps / kmp.json: 
  `<Examples><Example Text="..." Note="..." Keys="Ctrl+Shift+X A B" /></Examples>`, 
  `"examples": [{ "text": "...", "note": "...", "keys": "Ctrl+Shift+X A B"}]`

- [x] common: update .kps schema ➡ keymanapp/keyman#9459
- [x] common: Update kmp.json schema ➡ keymanapp/keyman#9459
- [x] common: Update keyboard_info schema to support keys textual form ➡ keymanapp/keyman#9459, keymanapp/keyman#9471
- [x] tike: update package editor ➡ keymanapp/keyman#9459
- [x] kmc-package: update compiler ➡ keymanapp/keyman#9459
- [x] kmc-keyboard-info: update compiler ➡ keymanapp/keyman#9474
- [x] help: document move from example to examples, looser structure ➡ keymanapp/help.keyman.com#798
- [x] #9708
- [x] keyboards: Move the metadata into .kps ➡ keymanapp/keyboards#2409
- [ ] #9710
- [ ] help.keyman.com: Update user docs, e.g. 'context/edit-language-example'
- [ ] api.keyman.com: update kmw rest api to return `examples` instead of `example`
- [ ] keymanweb.com: parse key sequence string

### `displayName`, `languageName`, `scriptName`, `regionName` fields
No change -- always generated automatically from BCP 47

- [x] help: Update generation data ➡ keymanapp/help.keyman.com#798

## `links` field

**Action:**: Only 11 uses, plus some empty arrays. Suggest not supporting in .kps.

- [x] keymanapp/keyboards: Move references into the description field, deprecate. ➡ keymanapp/keyboards#2337
- [x] keymanapp/keyboards: Move links in the legacy keyboard_info files into the description field ➡ keymanapp/keyboards#2337
- [x] common: remove from schema ➡ keymanapp/keyman#9452
- [x] help: remove `links` ➡ keymanapp/help.keyman.com#798

## `related` field

**Action:** on `deprecates` and `note` subfields
* `deprecates`: add to .kps, a list of ids in `<RelatedKeyboards><RelatedKeyboard Id="id" Deprecates="True" /></RelatedKeyboards>`
* `note`: only used in sil_ipa to ref ipa93_km5, so effectively unused; remove it.

- [x] Update .kps schema ➡ keymanapp/keyman#9459
- [x] Update kmp.json schema ➡ keymanapp/keyman#9459
- [x] Update compiler ➡ keymanapp/keyman#9459
- [x] Update package editor ➡ keymanapp/keyman#9459
- [x] keymanapp/keyboards: remove `notes` field ➡ keymanapp/keyboards#2337
- [x] help: update generation data, remove `note` ➡ keymanapp/help.keyman.com#798
- [x] kmc-keyboard-info: update compiler ➡ keymanapp/keyman#9474
- [x] keyboards: move related keyboard data into the .kps files ➡ keymanapp/keyboards#2410
- [ ] help.keyman.com: context/edit-related-package
  
## `legacyId` field

**Action:** only in legacy keyboards, never generated. Remove altogether as obsolete.

- [x] common: remove from schema ➡ keymanapp/keyman#9452
- [x] keymanapp/keyboards: remove from all .keyboard_info (including those in legacy/) field ➡ keymanapp/keyboards#2337
- [x] Help: remove ➡ keymanapp/help.keyman.com#798

## `documentationFilename` field
**Action:**: only used in legacy/ keyboards, remove it

- [x] keymanapp/keyboards: remove field ➡ keymanapp/keyboards#2337
- [x] common: remove from schema ➡ keymanapp/keyman#9452
- [x] Help: remove ➡ keymanapp/help.keyman.com#798

## `documentationFileSize` field

**Action:** only used in legacy/ keyboards, remove it

- [x] keymanapp/keyboards: remove field ➡ keymanapp/keyboards#2337
- [x] common: remove from schema ➡ keymanapp/keyman#9452
- [x] Help: remove ➡ keymanapp/help.keyman.com#798

-------

Should not require changes to end-user apps, although they could benefit from some of the additional metadata in the future, e.g. showing key sequence to type a sample string in the keyboard.

e.g. see https://github.com/keymanapp/keyboards/pull/2308#issuecomment-1645373474

**Comment by darcywong00** [comment]
Would this also flag if the .model_info or .keyboard_info doesn't match the package ID? e.g. the fix needed in  keymanapp/keyboards#2319

**Comment by mcdurdin** [comment]
> Would this also flag if the .model_info or .keyboard_info doesn't match the package ID? e.g. the fix needed in keymanapp/keyboards#2319

Well, it just wouldn't find the .model_info or .keyboard_info so it would build defaults. It would mean it wouldn't "go wrong" in the deployment like it did for that PR, but the results still may not be what the dev expected because the misspelled .keyboard_info would still be ignored.

**Comment by mcdurdin** [comment]
In auditing the keyboards repo, I determined that we no longer have any keyboards that are only .js. All keyboards have a .kmp.

The following command lists keyboards that have no .kmp file, running e.g. from release/:
```
find . -mindepth 2 -maxdepth 2 -type d '!' -exec sh -c 'ls -1 "{}/build"|egrep -i -q ".kmp$"' ';' -print
```

It also prints an error if there is no build/ folder, e.g. if you failed to build the keyboard.

---

There are still many keyboards that do not have a .kmx:

* fv/fv_anicinapemi8in
* fv/fv_anishinaabemowin
* fv/fv_atikamekw
* fv/fv_australian
* fv/fv_blackfoot
* fv/fv_bodewadminwen
* fv/fv_cree_latin
* fv/fv_dakota_mb
* fv/fv_dakota_sk
* fv/fv_denesuline
* fv/fv_dene_dzage
* fv/fv_dene_mb
* fv/fv_dene_nt
* fv/fv_dene_zhatie
* fv/fv_dexwlesucid
* fv/fv_dine_bizaad
* fv/fv_eastern_canadian_inuktitut
* fv/fv_goyogohono
* fv/fv_hulquminum
* fv/fv_ilnu_innu_aimun
* fv/fv_inuvialuktun
* fv/fv_isga_iabi
* fv/fv_kashogotine_yati
* fv/fv_klahoose
* fv/fv_lakota
* fv/fv_lunaapeewi_huluniixsuwaakan
* fv/fv_maori
* fv/fv_moose_cree
* fv/fv_nakoda
* fv/fv_naskapi
* fv/fv_neeaandeg
* fv/fv_neeaaneegn
* fv/fv_nexwslayemucen
* fv/fv_nlha7kapmxtsin
* fv/fv_northern_east_cree
* fv/fv_nuxalk
* fv/fv_ojibwa
* fv/fv_onayotaaka
* fv/fv_onodagega_onondagega
* fv/fv_onodowaga
* fv/fv_plains_cree
* fv/fv_sahugotine_yati
* fv/fv_severn_ojibwa
* fv/fv_shihgotine_yati
* fv/fv_skaru_re
* fv/fv_skicinuwatuwewakon
* fv/fv_skwxwumesh_snichim
* fv/fv_southern_carrier
* fv/fv_swampy_cree
* fv/fv_tlicho_yatii
* fv/fv_tsuutina
* fv/fv_uummarmiutun
* fv/fv_wendat
* fv/fv_wobanakiodwawogan
* gff/gff_amharic_classic
* gff/gff_harege_fidelat
* gff/gff_mesobe_fidelat
* i/inuktitut_latin
* i/inuktitut_pirurvik
* nrc/nrc_crk_cans
* t/tohono_oodham

For these, we will get as much as we can from the .kmp and fallback to .js for the few fields which are not yet available in the package.
