### ISSUE TITLE
bug(core): ldml key-not-found not quite right 🙀 

### ISSUE THREAD

**Issue by srl295** [keymanapp/keyman#9451]
From review at https://github.com/keymanapp/keyman/pull/9405/files#r1289675373

> Some frame keys cause a context invalidation. Frame keys and modifier keys etc then get kicked back to the OS, but any US English character-generating key gets added as an action

ldml processor doesn't do this yet.

Also see https://unicode-org.atlassian.net/browse/CLDR-17262 we may need some spec improvement here.

**Comment by mcdurdin** [comment]
> but any US English character-generating key gets added as an action

Note that we resolved that unassigned keys do nothing on ldml keyboards.

**Comment by srl295** [comment]
> > but any US English character-generating key gets added as an action
> 
> Note that we resolved that unassigned keys do nothing on ldml keyboards.

okay, but in reading the kmx code, i'm not sure how I distinguish between an unassigned key and a "frame key and modifier etc".  

Do i need to check for   `KM_CORE_VKEY_ENTER ||   KM_CORE_VKEY_SHIFT || … ||  KM_CORE_VKEY_PRTSCN` etc?

I could check for _every base vkey that could occur on the scancodes lists…_  Then I would know which vkeys were expected to be mappable by ldml.  So `K_A` if unmapped would do nothing but `K_ENTER` would be passed through to the OS?

**Comment by srl295** [comment]
Comments here:
- [ ] there isn't a KMX+ representation for the 'new' `<form>` element. probably needs a new ticket for that. If I had that, I could look for 'expected scancodes'.
- [ ] If a key is a 'gap' and you press that key, right now it probably looks like a key with a 0-length string output.   Could probably short circuit this (and any other situation where a key has a 0-length output for that matter) and do a little less processing. , basically ignored.
- [ ] kmc currently only fills in keys in the rows and columns until it runs out of input from the xml.  This means that `<row keys="A gap gap B"/>` only fills in four entries, for A, gap, gap, B.   It _could_ actually complete the row, perhaps automatically assigning the 'missing keys' to `gap`, or better yet a 0-length keystring simply meaning a missing key.   If this were done, then the `kmap` subtable would have _every expected vkey_ filled in.  And a lookup for those vk ids would always succeed, but return either the 'null' key or a `gap` key.  In any event, the key could then be processed by ignoring it (no output).  Whereas any frame key would _not_ match these vkeys and could then be passed on to the OS.

**Comment by srl295** [comment]
```
- key action: ['K_BKQUOTE' 0xc0]/modifier Unmodified 0x0
Execute debugger commands using "-exec <command>", for example "-exec info registers" will list registers in use (when GDB is the debugger)
Loaded '/usr/lib/swift/libswiftCore.dylib'. Symbols loaded.
context   : U+0061  [a]
testcontext U+61 
context   : U+0061  [a]
- key action: ['K_1' 0x31]/modifier Unmodified 0x0
context   : U+0061  [a]
testcontext U+61 
context   : U+0061  [a]
- key action: ['K_ENTER' 0xd]/modifier Unmodified 0x0
action: context invalidated (markers cleared)
action: emit keystroke
context   : U+0061  [a]
testcontext U+61 
context   : U+0061  [a]
- check expected
```

I have this working locally (PR in progress) where it distinguishes between a gap key (`K_1` above - no output, no action happens) and an 'unmapped' key (`K_ENTER` above where it shows context invalidated and emit keystroke).  i'm not sure how to test for this though. Maybe something with showing markers were cleared, that seems indirect.

**Comment by srl295** [comment]
^ PTAL https://github.com/keymanapp/keyman/pull/10090

**Comment by mcdurdin** [comment]
> I have this working locally (PR in progress) where it distinguishes between a gap key (`K_1` above - no output, no action happens) and an 'unmapped' key (`K_ENTER` above where it shows context invalidated and emit keystroke). i'm not sure how to test for this though. Maybe something with showing markers were cleared, that seems indirect.

Also, modifier keys (incl. Caps) should not invalidate context.

**Comment by srl295** [comment]
> > I have this working locally (PR in progress) where it distinguishes between a gap key (`K_1` above - no output, no action happens) and an 'unmapped' key (`K_ENTER` above where it shows context invalidated and emit keystroke). i'm not sure how to test for this though. Maybe something with showing markers were cleared, that seems indirect.
> 
> Also, modifier keys (incl. Caps) should not invalidate context.

okay… _how do i know_ if the vkey is a modifier key? do i need a list K_SHIFT, K_CAPS, etc?

**Comment by mcdurdin** [comment]
> do i need a list K_SHIFT, K_CAPS, etc?

One sample from kmn:

https://github.com/keymanapp/keyman/blob/6669d232a606420715f3c6f6f7c7baa0669f9d3d/windows/src/engine/keyman32/k32_lowlevelkeyboardhook.cpp#L62-L76

We have a truth table for context reset:

[windows/src/engine/keyman32/VKScanCodes.cpp](https://github.com/keymanapp/keyman/blob/738e1946a6c5a04cd67365c26252bcfc4c0cb973/windows/src/engine/keyman32/VKScanCodes.cpp#L294-L566)

This comment in Keyman Engine for Windows may be interesting background:

https://github.com/keymanapp/keyman/blob/0406cb1381c6c95d436aeeb33b115cf7f09c68dd/windows/src/engine/keyman32/keybd_shift.cpp#L25-L62

**Comment by srl295** [comment]
@mcdurdin thanks, sounds like i have the data i need!

**Comment by mcdurdin** [comment]
> @mcdurdin thanks, sounds like i have the data i need!

Happy for second-guessing on some of the decisions on the vkcontextreset array -- it was done a long time ago and reasons are lost in the mists of time

**Comment by srl295** [comment]
Still TODO:
 - developer should map all possible vkeys to gaps

**Comment by srl295** [comment]
Fixed by #10236
